### ISSUE TITLE
Device farm configuration doesn't support both as platform

### ISSUE THREAD

**Issue by SudhanvaManjunath** [AppiumTestDistribution/AppiumTestDistribution#1032]
Hey @saikrishna321 I am using ATD with appium device farm plugin, Currently I can only run device farm either for android or for ios, If I need to run it for both at once, then with current implementation its not possible.

Below is the caps example

`"serverConfig": {
    "server": {
      "port": 31337,
      "use-plugins": [
        "device-farm",
        "appium-dashboard",
        "element-wait"
      ],
      "plugin": {
        "device-farm": {
          "platform": "both",
          "skipChromeDownload": true
        }
      }
    }
  }`

**Comment by saikrishna321** [comment]
You cannot run both from ATD. You need to have separate pipelines for android and iOS.
