### ISSUE TITLE
Master branch has compilation Error 

### ISSUE THREAD

**Issue by SushanthN** [AppiumTestDistribution/AppiumTestDistribution#1033]
<img width="1430" alt="image" src="https://github.com/AppiumTestDistribution/AppiumTestDistribution/assets/54350763/2dbf8006-d138-489a-b943-0a1eeb543a8b">

@saikrishna321 @harikrishnan83 @SrinivasanTarget @anandbagmar Updating Java-client from 8.2.0 to 8.3.0 solves this issue. Please have a look

**Comment by saikrishna321** [comment]
Main has java-client version 8.5.0

**Comment by SushanthN** [comment]
@saikrishna321 We are using master branch as of now because main branch has appium 2.0 and we have not yet migrated. So can you please resolve compilation error of master branch.

**Comment by saikrishna321** [comment]
@SushanthN sorry, as appium does not support v1.0, so we dropped support. Feel free to raise PR or maintain ur folk.
