### ISSUE TITLE
How to continue run tests when app crash?

### ISSUE THREAD

**Issue by shaynl** [AppiumTestDistribution/AppiumTestDistribution#106]
I found out that if the app crash with one of my tests it stop running all the rest of the tests on same device (other devices continue to run). I think this is only for IOS.
When this happens I see the following error:

> org.openqa.selenium.remote.SessionNotFoundException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 5 milliseconds
> Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' 

Is there any way to catch that error and restart the driver to continue run the rest of my tests?

**Comment by saikrishna321** [comment]
@shaynl i don't this would happen, in the @BeforeMethod we are creating the driver instance and that should bring the crashed app. Is there any sample project which we can reproduce ..

**Comment by shaynl** [comment]
I can't share the app but this is my @BeforeMethod and @AfterMethod setup: 

@BeforeMethod() public void startApp(Method name) throws Exception {
        driver = startAppiumServerInParallel(name.getName(),iosNative(),androidNative());
        startLogResults(name.getName());
    }
@AfterMethod() public void killServer(ITestResult result)
        throws InterruptedException, IOException, URISyntaxException {
        endLogTestResults(result);
        getDriver().quit();
    }
I now test it by killing the app manually on the iphone and got same result. I see a lot of this in the log after kiling the app: 
SKIPPED CONFIGURATION: @BeforeMethod startApp
SKIPPED CONFIGURATION: @AfterMethod killServer

**Comment by saikrishna321** [comment]
@SrinivasanTarget ping

**Comment by SrinivasanTarget** [comment]
@shaynl We will investigate and get back to you on the behavior of Appium

**Comment by saikrishna321** [comment]
@shaynl i'm unable to reproduce it on android. I forced killed the app manually and went ahead with debugging and i got the below error.

org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

@SrinivasanTarget can you try with iOS?

**Comment by shaynl** [comment]
@saikrishna321 I also didn't see this on Android. It seems to happened only with IOS.
