### ISSUE TITLE
Is screenshots and log links should work now with ExtentX 0.2.2?

### ISSUE THREAD

**Issue by shaynl** [AppiumTestDistribution/AppiumTestDistribution#134]
I'm on the latest code and I still don't see screenshots and logs in ExtentX (only in ExtentReport.html). Is there any fix/workaround for that?

**Comment by saikrishna321** [comment]
@shaynl haven't give it a try .. will look into

**Comment by hemano** [comment]
@saikrishna321 Will this PR solve this issue?

https://github.com/saikrishna321/AppiumTestDistribution/pull/198

**Comment by saikrishna321** [comment]
We deprecated ExtentReports. Pls use Reportportal
