### ISSUE TITLE
Taking a failure screenshot needs check that app did not crash

### ISSUE THREAD

**Issue by brtu** [AppiumTestDistribution/AppiumTestDistribution#181]
Right now, if the app crashes then the test will fail.  AppiumTestDistribution will then attempt to take a failure screenshot.  Taking a screenshot will throw an exception because the driver can't connect to the app session.

I think a fix would be to check that the driver session still exists and is valid before taking the screenshot.  I also started using flick https://github.com/isonic1/flick to take the screenshot because it is able to take screenshots on the device even if the app crashes.

**Comment by saikrishna321** [comment]
@brtu i have seen some crashes in my CI and still the framework takes screenshot, do you have error stack? We use flick as part of framework, if needed then we can add that to capture screenshot

**Comment by brtu** [comment]
Unfortunately I think the exception error stack (from AppiumTestDistribution taking the screenshot) was getting swallowed up and did not appear in the logs.  Only the Appium webdriver exception appears.

Here is a snippet:
`uild	02-Apr-2017 02:40:12	[debug] [UIAuto] Socket data received (8192 bytes)
build	02-Apr-2017 02:40:12	[debug] [UIAuto] Socket data received (7508 bytes)
build	02-Apr-2017 02:40:12	[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"Receptiv Provisioned","label":"Receptiv Provisioned","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":320,"height":568},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom
build	02-Apr-2017 02:40:12	[debug] [UIAuto] Sending command to instruments: au.getElementsByIndexPaths(["/0/0/9/0"])
build	02-Apr-2017 02:40:12	[debug] [Instruments] [INST] 2017-04-02 02:40:12 +0000 Fail: The target application appears to have died
build	02-Apr-2017 02:40:12	[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 71.695335s; Output : /Users/MBMobile/bamboo-agent-home/xml-data/build-dir/MA-SI8T-JOB1/target/tmp_62344/appium-instruments/instrumentscli0.trace)
build	02-Apr-2017 02:40:12	[debug] [Instruments] Instruments exited with code: 0
build	02-Apr-2017 02:40:13	[debug] [iOS] Deleting ios session
build	02-Apr-2017 02:40:13	[debug] [UIAuto] Closing socket server.
build	02-Apr-2017 02:40:13	[debug] [UIAuto] Instruments socket server was closed
build	02-Apr-2017 02:40:13	[Appium] Closing session, cause was 'An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination!'
build	02-Apr-2017 02:40:13	[Appium] Removing session d6ee63c6-66cc-4786-8ccf-af6535fe9021 from our master session list
build	02-Apr-2017 02:40:13	[debug] [Instruments] Starting shutdown.
build	02-Apr-2017 02:40:13	[debug] [iOSLog] Stopping iOS log capture
build	02-Apr-2017 02:40:13	[debug] [iOS] Not clearing log files. Use `clearSystemFiles` capability to turn on.
build	02-Apr-2017 02:40:13	[debug] [iOS] Creating iDevice object with udid edc0ae2953b6a9316cfc0cf5c2dfca8b9737594c
build	02-Apr-2017 02:40:13	[debug] [iOS] Running ios real device reset flow
build	02-Apr-2017 02:40:13	[HTTP] <-- POST /wd/hub/session/d6ee63c6-66cc-4786-8ccf-af6535fe9021/elements 500 3610 ms - 204 
error	02-Apr-2017 02:40:13	Apr 01, 2017 10:40:13 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
error	02-Apr-2017 02:40:13	WARNING: WebDriverException thrown by findElement(By.xpath: //UIAApplication[1]/*/*/UIAWebView[1])
error	02-Apr-2017 02:40:13	org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination! (WARNING: The server did not provide any stacktrace information)
error	02-Apr-2017 02:40:13	Command duration or timeout: 3.63 seconds
error	02-Apr-2017 02:40:13	Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
error	02-Apr-2017 02:40:13	System info: host: 'Automation-Mac-mini.local', ip: 'fe80:0:0:0:4a8:9d70:3d:46fa%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_72'
error	02-Apr-2017 02:40:13	Driver info: io.appium.java_client.ios.IOSDriver
error	02-Apr-2017 02:40:13	Capabilities [{app=/Users/MBMobile/Documents/apps/Receptiv.ipa, networkConnectionEnabled=false, bundleId=com.mediabrix.ReceptivProvisioned, databaseEnabled=false, deviceName=QA/Dev iOS 8
error	02-Apr-2017 02:40:13	, platform=MAC, desired={app=/Users/MBMobile/Documents/apps/Receptiv.ipa, platformVersion=8.4, bundleId=com.mediabrix.ReceptivProvisioned, udid=edc0ae2953b6a9316cfc0cf5c2dfca8b9737594c, platformName=iOS, deviceName=QA/Dev iOS 8
error	02-Apr-2017 02:40:13	, autoAcceptAlerts=true}, platformVersion=8.4, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=edc0ae2953b6a9316cfc0cf5c2dfca8b9737594c, platformName=iOS, autoAcceptAlerts=true}]
error	02-Apr-2017 02:40:13	Session ID: d6ee63c6-66cc-4786-8ccf-af6535fe9021
error	02-Apr-2017 02:40:13	*** Element info: {Using=xpath, value=//UIAApplication[1]/*/*/UIAWebView[1]}
error	02-Apr-2017 02:40:13		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
error	02-Apr-2017 02:40:13		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
error	02-Apr-2017 02:40:13		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
error	02-Apr-2017 02:40:13		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
error	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
error	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
error	02-Apr-2017 02:40:13		at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:396)
error	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:54)
error	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:168)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:480)
error	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.findElementsByXPath(DefaultGenericMobileDriver.java:144)
error	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.findElementsByXPath(AppiumDriver.java:200)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:359)
error	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:50)
error	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:164)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:898)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:208)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:204)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:654)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:647)
error	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
error	02-Apr-2017 02:40:13		at com.appium.config.CommonAppiumTest.waitForElementClickableByLocator(CommonAppiumTest.java:20)
error	02-Apr-2017 02:40:13		at com.appium.screen.flows.iOSFlow.confirmAdStart(iOSFlow.java:84)
error	02-Apr-2017 02:40:13		at com.appium.pages.HomePage.confirmAdStart(HomePage.java:87)
error	02-Apr-2017 02:40:13		at com.appium.steps.PlayAdSteps.verifyAdStart(PlayAdSteps.java:212)
error	02-Apr-2017 02:40:13		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
error	02-Apr-2017 02:40:13		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
error	02-Apr-2017 02:40:13		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
error	02-Apr-2017 02:40:13		at java.lang.reflect.Method.invoke(Method.java:498)
error	02-Apr-2017 02:40:13		at cucumber.runtime.Utils$1.call(Utils.java:37)
error	02-Apr-2017 02:40:13		at cucumber.runtime.Timeout.timeout(Timeout.java:13)
error	02-Apr-2017 02:40:13		at cucumber.runtime.Utils.invoke(Utils.java:31)
error	02-Apr-2017 02:40:13		at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
error	02-Apr-2017 02:40:13		at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
error	02-Apr-2017 02:40:13		at cucumber.runtime.Runtime.runStep(Runtime.java:299)
error	02-Apr-2017 02:40:13		at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
error	02-Apr-2017 02:40:13		at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
error	02-Apr-2017 02:40:13		at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
error	02-Apr-2017 02:40:13		at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
error	02-Apr-2017 02:40:13		at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
error	02-Apr-2017 02:40:13		at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
error	02-Apr-2017 02:40:13		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
error	02-Apr-2017 02:40:13		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
error	02-Apr-2017 02:40:13		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
error	02-Apr-2017 02:40:13		at java.lang.reflect.Method.invoke(Method.java:498)
error	02-Apr-2017 02:40:13		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
error	02-Apr-2017 02:40:13		at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
error	02-Apr-2017 02:40:13		at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
error	02-Apr-2017 02:40:13		at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
error	02-Apr-2017 02:40:13		at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
error	02-Apr-2017 02:40:13		at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
error	02-Apr-2017 02:40:13		at org.testng.TestRunner.privateRun(TestRunner.java:782)
error	02-Apr-2017 02:40:13		at org.testng.TestRunner.run(TestRunner.java:632)
error	02-Apr-2017 02:40:13		at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
error	02-Apr-2017 02:40:13		at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
error	02-Apr-2017 02:40:13		at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
error	02-Apr-2017 02:40:13		at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
error	02-Apr-2017 02:40:13		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
error	02-Apr-2017 02:40:13		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
error	02-Apr-2017 02:40:13		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
error	02-Apr-2017 02:40:13		at java.lang.Thread.run(Thread.java:745)
error	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	[HTTP] --> GET /wd/hub/session/d6ee63c6-66cc-4786-8ccf-af6535fe9021/context {}
build	02-Apr-2017 02:40:13	[HTTP] <-- GET /wd/hub/session/d6ee63c6-66cc-4786-8ccf-af6535fe9021/context 404 5 ms - 131 
build	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	0 Scenarios ()
build	02-Apr-2017 02:40:13	8 Steps ([31m1 failed[0m, [32m7 passed[0m)
build	02-Apr-2017 02:40:13	1m6.018s
build	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination! (WARNING: The server did not provide any stacktrace information)
build	02-Apr-2017 02:40:13	Command duration or timeout: 3.63 seconds
build	02-Apr-2017 02:40:13	Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
build	02-Apr-2017 02:40:13	System info: host: 'Automation-Mac-mini.local', ip: 'fe80:0:0:0:4a8:9d70:3d:46fa%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_72'
build	02-Apr-2017 02:40:13	Driver info: io.appium.java_client.ios.IOSDriver
build	02-Apr-2017 02:40:13	Capabilities [{app=/Users/MBMobile/Documents/apps/Receptiv.ipa, networkConnectionEnabled=false, bundleId=com.mediabrix.ReceptivProvisioned, databaseEnabled=false, deviceName=QA/Dev iOS 8
build	02-Apr-2017 02:40:13	, platform=MAC, desired={app=/Users/MBMobile/Documents/apps/Receptiv.ipa, platformVersion=8.4, bundleId=com.mediabrix.ReceptivProvisioned, udid=edc0ae2953b6a9316cfc0cf5c2dfca8b9737594c, platformName=iOS, deviceName=QA/Dev iOS 8
build	02-Apr-2017 02:40:13	, autoAcceptAlerts=true}, platformVersion=8.4, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=edc0ae2953b6a9316cfc0cf5c2dfca8b9737594c, platformName=iOS, autoAcceptAlerts=true}]
build	02-Apr-2017 02:40:13	Session ID: d6ee63c6-66cc-4786-8ccf-af6535fe9021
build	02-Apr-2017 02:40:13	*** Element info: {Using=xpath, value=//UIAApplication[1]/*/*/UIAWebView[1]}
build	02-Apr-2017 02:40:13		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
build	02-Apr-2017 02:40:13		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
build	02-Apr-2017 02:40:13		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
build	02-Apr-2017 02:40:13		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
build	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
build	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
build	02-Apr-2017 02:40:13		at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:396)
build	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:54)
build	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:168)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:480)
build	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.findElementsByXPath(DefaultGenericMobileDriver.java:144)
build	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.findElementsByXPath(AppiumDriver.java:200)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:359)
build	02-Apr-2017 02:40:13		at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:50)
build	02-Apr-2017 02:40:13		at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:164)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:898)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:208)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:204)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:654)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:647)
build	02-Apr-2017 02:40:13		at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
build	02-Apr-2017 02:40:13		at com.appium.config.CommonAppiumTest.waitForElementClickableByLocator(CommonAppiumTest.java:20)
build	02-Apr-2017 02:40:13		at com.appium.screen.flows.iOSFlow.confirmAdStart(iOSFlow.java:84)
build	02-Apr-2017 02:40:13		at com.appium.pages.HomePage.confirmAdStart(HomePage.java:87)
build	02-Apr-2017 02:40:13		at com.appium.steps.PlayAdSteps.verifyAdStart(PlayAdSteps.java:212)
build	02-Apr-2017 02:40:13		at âœ½.Then ad should start(features/LegoTemplate/Smoke_Rescue_Video.feature:13)
build	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	None of the features at [classpath:features/LegoTemplate/Smoke_Rescue_Vizu.feature] matched the filters: [@legobasicsmoke,@sdk1844basicsmoke]
build	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	0 Scenarios
build	02-Apr-2017 02:40:13	0 Steps
build	02-Apr-2017 02:40:13	0m0.000s
build	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	None of the features at [classpath:features/LegoTemplate/Smoke_Rescue_Vizu_Video.feature] matched the filters: [@legobasicsmoke,@sdk1844basicsmoke]
build	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	0 Scenarios
build	02-Apr-2017 02:40:13	0 Steps
build	02-Apr-2017 02:40:13	0m0.000s
build	02-Apr-2017 02:40:13	
build	02-Apr-2017 02:40:13	Parallel Thread is::Thread_0
build	02-Apr-2017 02:40:13	[Ljava.lang.String;@a7b7a7f`

Note that the app crashed ("[Instruments] [INST] 2017-04-02 02:40:12 +0000 Fail: The target application appears to have died") and then the test case failed.  Then AppiumTestDistribution attempts to take a failure screenshot.  My Cucumber @After steps were never executed because the screenshot threw an exception.

I believe that you can manually reproduce this error by force closing the app in the middle of running a test.
