### ISSUE TITLE
NullPointerException when run through terminal ExtentX="true" mvn clean -Dtest=Runner test

### ISSUE THREAD

**Issue by ssrikantasahoo** [AppiumTestDistribution/AppiumTestDistribution#188]
estApp(com.test.site.Runner)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.NullPointerException
	at com.test.site.Runner.testApp(Runner.java:16)

Results :

Failed tests:   testApp(com.test.site.Runner)

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.765 s
[INFO] Finished at: 2017-05-13T12:29:56+05:30
[INFO] Final Memory: 29M/395M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project AppiumTestDistribution: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/srikantakumarsahoo/AppiumTestDistribution/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by saikrishna321** [comment]
can u post your config.properties and Runner.java code snippet

**Comment by ssrikantasahoo** [comment]
config.propperties
#APP_PATH=/Users/saikrisv/Downloads/***.ipa
APP_PACKAGE=com.android2.calculator3
APP_ACTIVITY=com.android2.calculator3.Calculator
RUNNER=distribute
APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
#BUNDLE_ID=com.tesco.grocery
#IOS_APP_PATH=/Users/srinivasansekar/Downloads/Grocery-iOS-LIVE-debug-293.ipa
ANDROID_APP_PATH=
FRAMEWORK=testng
#MONGODB_SERVER=localhost
#MONGODB_PORT=27017
#MAX_RETRY_COUNT=2
#INCLUDE_GROUPS=smoke,regression
#EXCLUDE_GROUPS=ignore,sanity
#CI_BASE_URI=http://Your_Jenkins_URL/path_to_your_project_till_root
  


runner.java

package com.test.site;

import com.appium.manager.ParallelThread;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Runner {
    @Test
    public static void testApp() throws Exception {
        //udid="f79219195208200d7710ca84a0305817567b31f8" mvn clean -Dtest=Runner test
        String udidParam = System.getenv("udid");
        String[] parts = udidParam.split(",");
        List<String> deviceList = Arrays.asList(parts);
        System.out.println(deviceList);
        ParallelThread parallelThread = new ParallelThread(deviceList);
        List<String> tests = new ArrayList<>();
        tests.add("HomePageTest6");
        //tests.add("HomePageTest3");
        //tests.add("HomePageTest4");
        boolean hasFailures = parallelThread.runner("com.test.site",tests);
        Assert.assertFalse(hasFailures, "Testcases have failed in parallel execution");
    }
}

**Comment by saikrishna321** [comment]
@ssrikantasahoo you have not provided the ANDROID_APP_PATH, pls provide that

**Comment by ssrikantasahoo** [comment]
can you tell i have to run only on ios parallel and distributed test???please

**Comment by saikrishna321** [comment]
@ssrikantasahoo you can connect both android and iOS devices to the same host mac and run the tests parallely, same set of tests will run on all devices connected
