### ISSUE TITLE
does README misses installing flick gem ?

### ISSUE THREAD

**Issue by vikramvi** [AppiumTestDistribution/AppiumTestDistribution#200]
@saikrishna321  Flick.java executes command **flick video ...** , which depends on flick gem https://github.com/isonic1/flick

isn't this be part of README as well ? I'm not getting without this gem installation how will it work. 
gem install flick

Please clarify

Thanks,
Vikram

**Comment by saikrishna321** [comment]
Thanks for pointing @vikramvi. Needs to me mentioned in ReadMe

**Comment by vikramvi** [comment]
strange that people are able to use framework recording feature without this gem, nobody raised query about this before ?
