### ISSUE TITLE
Need to modify reports, while using @DataProvider

### ISSUE THREAD

**Issue by hemano** [AppiumTestDistribution/AppiumTestDistribution#201]
<img width="1210" alt="screen shot 2017-07-13 at 1 15 12 pm" src="https://user-images.githubusercontent.com/10948392/28155457-78524604-67cc-11e7-942f-39f4176b8c1a.png">

@saikrishna321 
Logging to the reports happens outside the node. Can we make it happen inside the nodes?

**Comment by saikrishna321** [comment]
@SrinivasanTarget this involves lot of changes 

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTestListener.java#L101

we create the child node after the testMethod  execution, but in this case we need to create the node BeforeMethod and expose to users something as 

```
ReportManager.getChildNode().get().info("Infomation Inside the node");
```

**Comment by saikrishna321** [comment]
Closing - As extent report no longer exists in the repo
