### ISSUE TITLE
AppiumServerLogs link broken on ExtentReports

### ISSUE THREAD

**Issue by 99heitor** [AppiumTestDistribution/AppiumTestDistribution#250]
[This link ](https://i.imgur.com/Gkqkoim.png) is currently broken on the Extent Reports html output. It seems to expect a [naming scheme that includes the device ID and a method name](https://github.com/saikrishna321/AppiumTestDistribution/blob/1e01d684bd3094b91a923ccdb0aed2f2ab6878c7/src/main/java/com/appium/manager/ReportManager.java#L53), but the only file in the folder `/appiumlogs` is called `appium_logs.txt`.
I'm using version 7.0.1.

**Comment by saikrishna321** [comment]
As the framework moved towards single server session, we need to add the AppiumLogs to DashBoard

**Comment by saikrishna321** [comment]
Moved away from ExtentReports
