### ISSUE TITLE
How to run test on gradle?

### ISSUE THREAD

**Issue by unlimUA** [AppiumTestDistribution/AppiumTestDistribution#258]

**Comment by saikrishna321** [comment]
you can add the repository in your gradle 

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}


dependencies {
		compile 'com.github.saikrishna321: AppiumTestDistribution: c4ff66ccc7'
	}
```

**Comment by unlimUA** [comment]
I do that already.
how to run test with cmd from windows ?

**Comment by saikrishna321** [comment]
@SrinivasanTarget can you help on this....

**Comment by SrinivasanTarget** [comment]
Sure @saikrishna321 will update in sometime

**Comment by unlimUA** [comment]
@SrinivasanTarget thanks a lot!

**Comment by pawarvaibhav** [comment]
Any update on this one?

**Comment by eridaputra** [comment]
Any update on this? currently I'm on a project using gradle and need to run parallel too 🙇
