### ISSUE TITLE
Exception handling - Throws null pointer if there are not devices connected

### ISSUE THREAD

**Issue by shridharkalagi** [AppiumTestDistribution/AppiumTestDistribution#260]
This is my iOScapability
 "app": {
        "device":"./xyz.ipa"
      }
I'm running tests only on real devices. Null pointer exception is thrown if it's not connected as there is a simulator open in the background which makes device count as 1.

**Comment by saikrishna321** [comment]
@shridharkalagi instead of throwing null, we need to handle the exception and give a valid message to user.
