### ISSUE TITLE
Do you have similar implementation in Nodejs using webdriverio?

### ISSUE THREAD

**Issue by sumeetp4** [AppiumTestDistribution/AppiumTestDistribution#298]
I need to implement same using javascript and node.js. Any help?

**Comment by SrinivasanTarget** [comment]
@sumeetp4 Currently No. Feel free to build one keeping ATD as ref and we can help if any.

**Comment by saikrishna321** [comment]
@bsneha90 thoughts ?

**Comment by hariharanwebmail** [comment]
No have to develop the same again on nodejs
