### ISSUE TITLE
Can we run different script on multiple android devices and can we test syncing like chat (live update or message receive or not) by this project ?

### ISSUE THREAD

**Issue by Pushpank** [AppiumTestDistribution/AppiumTestDistribution#299]

**Comment by saikrishna321** [comment]
Yes, we can run multiple scripts on multiple device, just give Runner=distribute in your config.properties

**Comment by Pushpank** [comment]
Thank you for instant reply, one more thing how to specify that a particular test case run in 'A' device and another to 'B' device.

**Comment by saikrishna321** [comment]
No,we don't set the test cases to devices, we ideally let the framework decide to push the test to free device. 

SkipIf(platform= "iOS") // if you want to skip a specific test case on certain platform then u need to use this annotation

**Comment by Pushpank** [comment]
ohh, If we are using only android devices, is there any way to decide a  particular device or thread for a particular test. so we can test syncing

**Comment by saikrishna321** [comment]
> is there any way to decide a particular device or thread for a particular test

No, thats not how test distribution should work on queues
