### ISSUE TITLE
Tests are not executing in Parallel

### ISSUE THREAD

**Issue by arunaousula9421** [AppiumTestDistribution/AppiumTestDistribution#300]
Hi @saikrishna321, recently I have started using your amazing framework and was able to write couple tests. But when I run them on multiple devices they are not running in parallel instead they are running sequentially One after other device.

Here's is SetUp
capabilities.json

```
{
  "android": {
    "platformName": "android",
    "app": "./build/app.apk",
    "appPackage": "com.app.ie",
    "appActivity": "com.app.ie.ui.main.MainActivity",
    "uiautomator2ServerInstallTimeout": 60000,
    "deviceName": "android",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "https://github.com/saikrishna321/VodQaAdvancedAppium/raw/master/daft.zip"
    },
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": false,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10,
    "isHeadless": false,
    "fullReset": false
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "appiumServerPath": "/usr/local/lib/node_modules/appium/build/lib/main.js"
    }
  ]
}
```

Utils Class

```
public class Utils {
    DesiredCapabilities caps = new DesiredCapabilities();
    public AppiumDriver<MobileElement> driver;
    public static Properties prop = new Properties();
    static InputStream input = null;


    @BeforeClass
    public AppiumDriver<MobileElement> getDriver() throws IOException {
        input = new FileInputStream("property/android.properties");
        prop.load(input);
        if (prop.getProperty("platform").equals("android")) {
            androidSetup();
        } else {
            if (prop.getProperty("platform").equals("ios")) {
                System.out.println("For IOS");
            }
        }
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        return driver;
    }


    public void androidSetup() throws MalformedURLException {
        caps.setCapability("deviceName", "Android");
        caps.setCapability("app", System.getProperty("user.dir") + "/build/daftandroid-user-release.apk");
        caps.setCapability("package", "com.app.ie");
        caps.setCapability("appActivity", "com.app.ie.ui.main.MainActivity");
        caps.setCapability(AndroidMobileCapabilityType.APP_WAIT_ACTIVITY, "com.daft.ie.ui.main.MainActivity");
        driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
    }


    @AfterClass
    public void tearDown() {
        driver.quit();
    }
}
```

POM.xml
```
 <dependencies>
        <dependency>
            <groupId>com.github.saikrishna321</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>8.0.0</version>
        </dependency>

        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>LATEST</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20.1</version>
            </plugin>
        </plugins>
    </build>
```
config.properties

```
RUNNER=distribute
APPIUM_JS_PATH=/usr/local/lib/nod_modules/appium/build/lib/main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
FRAMEWORK=testng
DEVICE_PLATFORM=simulator
ANDROID_CAPS=/caps/capabilities.json
```
Can you please let me know how to fix this issue and run the tests in parallel.

**Comment by SrinivasanTarget** [comment]
@arunaousula9421 Thanks for your feedback :)
Few things,
1) Can you follow our wiki [here](https://github.com/saikrishna321/AppiumTestDistribution/wiki/Configure-tests-for-TestNG) Unfortunately it's little outdated. You can expect an update in wiki in another few days.
2) Driver creation is handled inside the framework so you don't need to worry about it. Update your utils class as per wiki.
3) Please check our release notes incase if you have any confusion on whats new in latest version.
4) If you find any discrepancies in doc, feel free to update us or make a PR 👍

**Comment by arunaousula9421** [comment]
Thank You @SrinivasanTarget. Can you please let me is there any potential issue at the moment to run the tests in parallel.

**Comment by SrinivasanTarget** [comment]
@arunaousula9421 As far as we know, there is no potential issues left out. If you figure out one feel free to raise here. Also dont forget to attach logs in form of gist.

**Comment by arunaousula9421** [comment]
@SrinivasanTarget Thank You. Only issue I found is tests were not running in parallel .. Rest everything looks amazing.

**Comment by SrinivasanTarget** [comment]
@arunaousula9421 Please follow the instructions and give a try as i see the utils class shared above is not meant for parallel. Also share the logs here in form of gist for us to investigate further

**Comment by saikrishna321** [comment]
@arunaousula9421 as srini said we had all the driver creation, i'm interested to see how the Utils class is used?

**Comment by arunaousula9421** [comment]
@saikrishna321 Can you please let me know where I am doing wrong in order to execute the tests in parallel. Here is my example test which I am executing

```
package com.appium.tests;

import com.appium.manager.AppiumDriverManager;
import com.appium.pages.HomePage;
import com.appium.pages.LoginPage;
import org.testng.annotations.Test;

import java.io.IOException;


/**
 * Created by arun on 09/03/2018.
 */
public class LoginTest {

    HomePage homePage;
    LoginPage loginPage;


    @Test
    public void loginWithValidUser() throws InterruptedException, IOException {
        homePage = new HomePage(AppiumDriverManager.getDriver());
        homePage.tapLogin().enterUserAndPassword("arunaousula", "dsch9421");
        //loginPage.tapLoginBtn();
    }
}

```

**Comment by arunaousula9421** [comment]
@SrinivasanTarget @saikrishna321 I was finally able to resolve the issue. Here's what I have found.
When I have updated the dependency to v8.0.0 and updated capabilities.json as above, tests were running serially. 

Now when I have moved back to previous version v7.0.0 and updated capabilities.json as [here](https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/caps/capabilities.json).

Tests were running in parallel.

**Comment by saikrishna321** [comment]
@arunaousula9421 i can't reproduce this on version 8.0.0. 

Can you post the server logs and video that would help

**Comment by SrinivasanTarget** [comment]
@arunaousula9421 Do you have data providers in your test?

**Comment by saikrishna321** [comment]
closing as inactive
