### ISSUE TITLE
using the command “Platform="android" mvn clean -Dtest=Runner test” cannot ran the test script

### ISSUE THREAD

**Issue by garinhu** [AppiumTestDistribution/AppiumTestDistribution#334]

**Comment by saikrishna321** [comment]
can you please show what the error logs look like

**Comment by garinhu** [comment]
when ran the command, show error "Platform" is not internal or external commands.
i see get the  'Platform' environment variable in code, but how to set the Env.?

**Comment by Siddh010** [comment]
In Eclipse IDE you can setup in Run Configuration ->Environment Option.
I am not sure  through  terminal.

**Comment by saikrishna321** [comment]
We should provide mvn clean test -Dtest=Runner test -DPlatform=android

And should add the property in maven surefire plugin.

            <configuration>
                <properties>
                    <Platform>${Platform}</Platform>
                </properties>
            </configuration>

**Comment by saikrishna321** [comment]
@mariosneo  

Run this command 

mvn clean test -Dtest=RunnerCukes test -DPlatform=android

**Comment by mariosneo** [comment]
Still running into an issue with the command mentioned. 

Here is my output :


`C:\Users\Admin\PageObjectPatternAppium-master>mvn clean test -Dtest=RunnerCukes test -DPlatform=android
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< com.pagepattern.appium:PagePatternAppium >--------------
[INFO] Building PagePatternAppium 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ PagePatternAppium ---
[INFO] Deleting C:\Users\Admin\PageObjectPatternAppium-master\target
[INFO]
[INFO] --- cucumber-jvm-parallel-plugin:4.2.0:generateRunners (generateRunners) @ PagePatternAppium ---
[INFO] Adding C:\Users\Admin\PageObjectPatternAppium-master\src\test\java to test-compile source root
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ PagePatternAppium ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Admin\PageObjectPatternAppium-master\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ PagePatternAppium ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ PagePatternAppium ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 19 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ PagePatternAppium ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 35 source files to C:\Users\Admin\PageObjectPatternAppium-master\target\test-classes
[INFO] /C:/Users/Admin/PageObjectPatternAppium-master/src/test/java/com/appium/config/CommonAppiumTest.java: Some input files use unchecked or unsafe operations.
[INFO] /C:/Users/Admin/PageObjectPatternAppium-master/src/test/java/com/appium/config/CommonAppiumTest.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ PagePatternAppium ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.appium.steps.RunnerCukes
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.451 s <<< FAILURE! - in com.appium.steps.RunnerCukes
[ERROR] testCukesRunner on testCukesRunner(com.appium.steps.RunnerCukes)(com.appium.steps.RunnerCukes)  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.IllegalArgumentException: Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test
        at com.appium.steps.RunnerCukes.testCukesRunner(RunnerCukes.java:11)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   RunnerCukes.testCukesRunner:11 » IllegalArgument Please execute with Platform ...
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.578 s
[INFO] Finished at: 2018-07-28T20:29:44+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project PagePatternAppium: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Admin\PageObjectPatternAppium-master\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

`

Here how my pom.xml and I have the following error:


Maven Model Inspection
pom.xml
Cannot resolve symbol 'Platform'


`<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.pagepattern.appium</groupId>
    <artifactId>PagePatternAppium</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <pluginRepositories>
        <pluginRepository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>com.github.saikrishna321</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>ef39d1cdd0</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>

        
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
                <configuration>
                    <properties>
                        <Platform>${Platform}</Platform>
                    </properties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>4.2.0</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            
                            <outputDirectory>src/test/java</outputDirectory>
                            
                            <glue>com.appium.steps</glue>
                            <featuresDirectory>src/test/resources/features</featuresDirectory>
                            <cucumberOutputDir>target</cucumberOutputDir>
                            <tags>
                                <tag>@login</tag>
                            </tags>
                            <namingScheme>simple</namingScheme>
                            
                            <namingPattern>Parallel{c}IT</namingPattern>
                            <parallelScheme>SCENARIO</parallelScheme>
                            <packageName>output</packageName>
                            <useTestNG>true</useTestNG>
                            <plugins>
                                <plugin>
                                    <name>com.cucumber.listener.ExtentCucumberFormatter</name>
                                </plugin>
                            </plugins>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>`

**Comment by saikrishna321** [comment]
@SudhiHathwar can you help here? 

@mariosneo r u running from command line or IDE?

**Comment by mariosneo** [comment]
From command line

**Comment by legendpc** [comment]
@mariosneo You can set environment variables for windows.

**Comment by mariosneo** [comment]
Thanks for the answer @legendpc but I can run a single test using this [class ](https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/src/test/java/com/appium/config/Utils.java) so I think is not an issue with the environment variables.

**Comment by ThanujaJ** [comment]
Is this issue resolved? Even am getting the same error

**Comment by mariosneo** [comment]
@ThanujaJ 
What is it your error exactly? What IDE are you using? I might can help

**Comment by orvilia** [comment]
Please provide solution to this...Can somebody provide the solution for windows....We are stuck

**Comment by saikrishna321** [comment]
@orvilia can you please try mvn clean -Dtest=Runner -DPlatform=android

**Comment by orvilia** [comment]
Hi,

We fixed the issue while providing system variable as Platform=android and running command “mvn clean -Dtest=Runner test”

But appium server is not starting. Do we need to set node.exe path somewhere for windows ??

Regards
Orivila

On 06-Dec-2018, at 5:03 PM, Sai Krishna <notifications@github.com<mailto:notifications@github.com>> wrote:


@orvilia<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forvilia&data=02%7C01%7C%7Cba9f35e14fce480e034408d65b6e9443%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636796927825642756&sdata=kPMVk8WAXq37GSpEKPT18ZPM%2B%2FhckITSxAT7iKNWV%2Fk%3D&reserved=0> can you please try mvn clean -Dtest=Runner -DPlatform=android

**Comment by saikrishna321** [comment]
> But appium server is not starting. Do we need to set node.exe path somewhere for windows ??

What error r u getting?  You can set appium server path 

https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/master/caps/capabilities.json#L27
