### ISSUE TITLE
make server capabilities seeded in caps.json

### ISSUE THREAD

**Issue by SrinivasanTarget** [AppiumTestDistribution/AppiumTestDistribution#341]
Update caps.json something like below and make server respect those caps,

```
"server" :{},
"android":{},
"ios": {}....
```

**Comment by SrinivasanTarget** [comment]
@SudhiHathwar would you like to pick this?

**Comment by SudhiHathwar** [comment]
@SrinivasanTarget  Ok i can pick this.

**Comment by saikrishna321** [comment]
Thanks @SrinivasanTarget this is much needed.

**Comment by SudhiHathwar** [comment]
@SrinivasanTarget @saikrishna321 @shridharkalagi 
Hi Guys,

The changes are pushed to a branch called serverCapabilities on ATD and RemoteAppiumManager Repo. Can you guys please check once?

If its good, i will raise the pull request .
