### ISSUE TITLE
Sample Project PageObjectPatternAppium not working

### ISSUE THREAD

**Issue by himgupta13** [AppiumTestDistribution/AppiumTestDistribution#347]
Getting Null pointer exception while running sample test with below capabilities in capabilities.json:
`testRunner(com.appium.tests.Runner)  Time elapsed: 14.172 sec  <<< FAILURE!
java.lang.NullPointerException: null
        at com.appium.utils.CapabilityManager.isApp(CapabilityManager.java:94)
        at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:38)
        at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
        at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
        at com.appium.tests.Runner.testRunner(Runner.java:13)`

``` {
  "android": {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "./build/wordpress.apk",
    "appPackage": "org.wordpress.android",
    "appActivity": "org.wordpress.android.ui.WPLaunchActivity",
    "deviceName": "emulator-5554",
    "noSign": true
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.3"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.3"
        }
      ]
    }
  ],
  "ATDServiceHost":"127.0.0.1",
  "ATDServicePort":"3000"
}

**Comment by SrinivasanTarget** [comment]
@himgupta13 Did you followed [this](https://github.com/saikrishna321/AppiumTestDistribution/wiki/Configure-tests-for-TestNG)?

**Comment by himgupta13** [comment]
As per the instructions,
My runner class:
```public class Runner {

        @Test public void testRunner() throws Exception {
            ParallelThread parallelThread = new ParallelThread();
            List<String> test = new ArrayList<String>();
            test.add("LoginTest");
            boolean runner = parallelThread.runner("com.appium.tests");
            System.out.println(runner);
            Assert.assertFalse(runner);
        }
```
config.properties file:
```RUNNER=parallel
APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
FRAMEWORK=testng
```

**Comment by saikrishna321** [comment]
@himgupta13 Runner is not able to find Test with TestNG can you please check the import in Runner class
