### ISSUE TITLE
[Reporting] Add Device Name along with platform and UDID in description

### ISSUE THREAD

**Issue by SrinivasanTarget** [AppiumTestDistribution/AppiumTestDistribution#373]
https://github.com/saikrishna321/AppiumTestDistribution/issues/350

**Comment by narayan907** [comment]
Hi
sometimes the above test description doesn't comes on report portal

**Comment by saikrishna321** [comment]
@narayan907 yah this is known issue on report portal as the listeners don't have execution order.

**Comment by narayan907** [comment]
Hi Sai
then how can we solve this problem,since description is necessary

**Comment by saikrishna321** [comment]
@narayan907 is this happening all the time or just a race condition ?

**Comment by narayan907** [comment]
Its happening very often,most of the items i am not able to see for decscription for any of the test cases...but whenever it comes it comes for all testcases

**Comment by saikrishna321** [comment]
@narayan907 are u talking about the test description which is added from TestNG @Test annotation or Device Name along with platform and UDID  in reportportal ?

**Comment by narayan907** [comment]
ya...about Device Name along with platform and UDID

**Comment by saikrishna321** [comment]
@narayan907  this is something that needs to be reported to report-portal. We have a new dashboard which will be published with next release
