### ISSUE TITLE
Extent Report is not displaying re-tried tests - MAX_RETRY_COUNT

### ISSUE THREAD

**Issue by spartanglady** [AppiumTestDistribution/AppiumTestDistribution#378]
When we set the property MAX_RETRY_COUNT=2, the generated extent report is not displaying the results of the tests that failed and re-executed the second time. For example, if I had five tests in my suite of which one failed and it is re-executed the second time and it got passed. The extent report displays as if only 4 tests were executed in that suite and it ignores the test that was retried.

**Comment by saikrishna321** [comment]
@spartanglady we no more support ExtentReporting as they were resulting in false failures, current master support report portal.  Pls give it a try http://reportportal.io/
