### ISSUE TITLE
Error while running through Distribute 

### ISSUE THREAD

**Issue by Shivashankarin91** [AppiumTestDistribution/AppiumTestDistribution#395]
Hi Sai, I have cloned your Page object Model project when I tired running through Distribute I am facing issue FOr detailed logs 
Please find the error logs in the below mentioned link:

https://gist.github.com/Shivashankarin91/110e53476f566738000ae111e5db49f9

**Comment by SrinivasanTarget** [comment]
@shridharkalagi FYA

**Comment by saikrishna321** [comment]
@Shivashankarin91 why is this reopened ?

**Comment by saikrishna321** [comment]
Fixed in v12.0.0
