### ISSUE TITLE
Don't force users to use ReportPortal/ReportPortal.properties as resources

### ISSUE THREAD

**Issue by SrinivasanTarget** [AppiumTestDistribution/AppiumTestDistribution#396]

**Comment by vsgopinath** [comment]
Just want to know when this issue will be closed. I am facing problem in getting reports in ReportPortal.io

**Comment by saikrishna321** [comment]
what is the issue ur facing ??

**Comment by orvilia** [comment]
As per your option provided in b008197, extent.html is not generating. How to make extent reports start working again.
