### ISSUE TITLE
There is no testng.xml file (pageObjectAppium) so how we run by group or testng

### ISSUE THREAD

**Issue by Pushpank** [AppiumTestDistribution/AppiumTestDistribution#405]
In pageOnjectAppium Master testng.xml file is not present so how we can run our test according to testng annotations or by group?

**Comment by saikrishna321** [comment]
@Pushpank ATD handles the execution on runtime, INCLUDE_GROUPS="yourgroups" mvn clean -Dtest=Runner test 

This will trigger the grouped tests
