### ISSUE TITLE
Nothing is to be tested

### ISSUE THREAD

**Issue by hhh3h** [AppiumTestDistribution/AppiumTestDistribution#414]
The testing by Cucumber is not executed.
I think "@smoke" must be tested but it is.
Please let me know what problem it is. T_T)

My IDE is Eclipse ...
man clean test -Dtest=RunnerCukes -DPlatform=android

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.test.cucumber.cukesrunner.RunnerCukes
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@567d299b
OUTPUT DIRECTORY :/Users/netmarble/eclipse-workspace/AppiumTestDistributionHHH/target
                            _  _        _ 
 _ __    __ _  _ __   __ _ | || |  ___ | |
| '_ \  / _` || '__| / _` || || | / _ \| |
| |_) || (_| || |   | (_| || || ||  __/| |
| .__/  \__,_||_|    \__,_||_||_| \___||_|
|_|                                       

***************************************************

Total Number of devices detected::1

***************************************************

starting running tests in threads
creating directory: Logs
Directory is created for device410014554d6ba153
creating directory: ADBLogs
Nov 27, 2018 2:26:42 PM com.appium.manager.DeviceAllocationManager getDevices
정보: All devices connected
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...

**************************************************************************

Starting Appium Server on Localhost......
**************************************************************************

Picking UserSpecified Path for AppiumServiceBuilder
(node:83076) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[Appium] Welcome to Appium v1.8.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 42624
[Appium]   log: /Users/netmarble/eclipse-workspace/AppiumTestDistributionHHH/target/appiumlogs/appium_logs.txt
[Appium] Appium REST http interface listener started on 127.0.0.1:42624
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 83
[HTTP] 
**************************************************************************

Appium Server Started at......http://127.0.0.1:42624/wd/hub
**************************************************************************

===============================================
    TestNG Test0
    Tests run: 0, Failures: 0, Skips: 0
===============================================

===============================================
TestNG Forum
Total tests run: 0, Failures: 0, Skips: 0
===============================================

*******androidSchema.json
*******iOSSchema.json
*******androidAndiOSSchema.json
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.79 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.267 s
[INFO] Finished at: 2018-11-27T14:26:44+09:00
[INFO] Final Memory: 29M/344M
[INFO] ------------------------------------------------------------------------

**Comment by saikrishna321** [comment]
@hhh3h you need to run this code 

https://github.com/AppiumTestDistribution/PageObjectPatternAppium
