### ISSUE TITLE
Cant able to detect the android device

### ISSUE THREAD

**Issue by Shivashankarin91** [AppiumTestDistribution/AppiumTestDistribution#418]

**Comment by Shivashankarin91** [comment]
Hi Sai,

I have imported the Page object model project when i tired to run its not runing through parallel mode
For details information please find the screenshot
![screen shot 2018-12-03 at 4 21 04 pm](https://user-images.githubusercontent.com/26323957/49370365-ef8c6a00-f719-11e8-8da4-6d651fc47c0c.png)

**Comment by saikrishna321** [comment]
I have seen this before, this is IDE issue. Try running it from command line it should work
