### ISSUE TITLE
Cucumber Scenario out line features are not executing 

### ISSUE THREAD

**Issue by KumarKola** [AppiumTestDistribution/AppiumTestDistribution#420]
Hi @saikrishna321  and @SrinivasanTarget  when i am trying to run the feature files which has scenario outlines i think while adding each step its not parsing <""> symbols.. I have attached logs here. 

"C:\Program Files\Java\jdk1.8.0_151\bin\java" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\lib\idea_rt.jar=22979:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\plugins\testng\lib\testng-plugin.jar;G:\test\PageObjectPatternAppium-master\target\test-classes;C:\Program Files\Java\jdk1.8.0_151\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\lib\junit-4.12.jar;C:\Users\Infinite\.m2\repository\com\github\saikrishna321\AppiumTestDistribution\9.0.1\AppiumTestDistribution-9.0.1.jar;C:\Users\Infinite\.m2\repository\io\appium\java-client\6.1.0\java-client-6.1.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-java\3.12.0\selenium-java-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.12.0\selenium-chrome-driver-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.12.0\selenium-edge-driver-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.12.0\selenium-firefox-driver-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.12.0\selenium-ie-driver-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.12.0\selenium-opera-driver-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.12.0\selenium-remote-driver-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.12.0\selenium-safari-driver-3.12.0.jar;C:\Users\Infinite\.m2\repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3.jar;C:\Users\Infinite\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-support\3.12.0\selenium-support-3.12.0.jar;C:\Users\Infinite\.m2\repository\org\seleniumhq\selenium\selenium-api\3.12.0\selenium-api-3.12.0.jar;C:\Users\Infinite\.m2\repository\cglib\cglib\3.2.6\cglib-3.2.6.jar;C:\Users\Infinite\.m2\repository\org\ow2\asm\asm\6.0\asm-6.0.jar;C:\Users\Infinite\.m2\repository\org\apache\ant\ant\1.9.6\ant-1.9.6.jar;C:\Users\Infinite\.m2\repository\org\apache\ant\ant-launcher\1.9.6\ant-launcher-1.9.6.jar;C:\Users\Infinite\.m2\repository\commons-validator\commons-validator\1.6\commons-validator-1.6.jar;C:\Users\Infinite\.m2\repository\commons-beanutils\commons-beanutils\1.9.2\commons-beanutils-1.9.2.jar;C:\Users\Infinite\.m2\repository\commons-digester\commons-digester\1.8.1\commons-digester-1.8.1.jar;C:\Users\Infinite\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;C:\Users\Infinite\.m2\repository\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;C:\Users\Infinite\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\Infinite\.m2\repository\org\springframework\spring-context\5.0.5.RELEASE\spring-context-5.0.5.RELEASE.jar;C:\Users\Infinite\.m2\repository\org\springframework\spring-aop\5.0.5.RELEASE\spring-aop-5.0.5.RELEASE.jar;C:\Users\Infinite\.m2\repository\org\springframework\spring-beans\5.0.5.RELEASE\spring-beans-5.0.5.RELEASE.jar;C:\Users\Infinite\.m2\repository\org\springframework\spring-core\5.0.5.RELEASE\spring-core-5.0.5.RELEASE.jar;C:\Users\Infinite\.m2\repository\org\springframework\spring-jcl\5.0.5.RELEASE\spring-jcl-5.0.5.RELEASE.jar;C:\Users\Infinite\.m2\repository\org\springframework\spring-expression\5.0.5.RELEASE\spring-expression-5.0.5.RELEASE.jar;C:\Users\Infinite\.m2\repository\org\aspectj\aspectjweaver\1.9.1\aspectjweaver-1.9.1.jar;C:\Users\Infinite\.m2\repository\org\openpnp\opencv\3.2.0-1\opencv-3.2.0-1.jar;C:\Users\Infinite\.m2\repository\com\github\temyers\cucumber-jvm-parallel-plugin\4.2.0\cucumber-jvm-parallel-plugin-4.2.0.jar;C:\Users\Infinite\.m2\repository\org\apache\velocity\velocity\1.7\velocity-1.7.jar;C:\Users\Infinite\.m2\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;C:\Users\Infinite\.m2\repository\io\cucumber\gherkin\3.2.0\gherkin-3.2.0.jar;C:\Users\Infinite\.m2\repository\io\cucumber\gherkin-jvm-deps\1.0.4\gherkin-jvm-deps-1.0.4.jar;C:\Users\Infinite\.m2\repository\org\projectlombok\lombok\1.16.10\lombok-1.16.10.jar;C:\Users\Infinite\.m2\repository\com\google\guava\guava\23.0\guava-23.0.jar;C:\Users\Infinite\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\Infinite\.m2\repository\com\google\errorprone\error_prone_annotations\2.0.18\error_prone_annotations-2.0.18.jar;C:\Users\Infinite\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\Infinite\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\Infinite\.m2\repository\org\jdom\jdom2\2.0.6\jdom2-2.0.6.jar;C:\Users\Infinite\.m2\repository\com\epam\reportportal\agent-java-testng\4.2.1-BETA\agent-java-testng-4.2.1-BETA.jar;C:\Users\Infinite\.m2\repository\com\epam\reportportal\client-java\4.0.9\client-java-4.0.9.jar;C:\Users\Infinite\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.8.10\jackson-annotations-2.8.10.jar;C:\Users\Infinite\.m2\repository\io\reactivex\rxjava2\rxjava\2.1.16\rxjava-2.1.16.jar;C:\Users\Infinite\.m2\repository\org\reactivestreams\reactive-streams\1.0.2\reactive-streams-1.0.2.jar;C:\Users\Infinite\.m2\repository\org\apache\tika\tika-core\1.4\tika-core-1.4.jar;C:\Users\Infinite\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\Infinite\.m2\repository\com\epam\reportportal\commons-model\4.2.0\commons-model-4.2.0.jar;C:\Users\Infinite\.m2\repository\io\swagger\swagger-annotations\1.5.13\swagger-annotations-1.5.13.jar;C:\Users\Infinite\.m2\repository\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;C:\Users\Infinite\.m2\repository\com\epam\reportportal\agent-java-cucumber\4.0.2\agent-java-cucumber-4.0.2.jar;C:\Users\Infinite\.m2\repository\com\epam\reportportal\logger-java-logback\4.0.0\logger-java-logback-4.0.0.jar;C:\Users\Infinite\.m2\repository\com\epam\reportportal\logger-java-log4j\4.0.1\logger-java-log4j-4.0.1.jar;C:\Users\Infinite\.m2\repository\net\masterthought\cucumber-reporting\3.8.0\cucumber-reporting-3.8.0.jar;C:\Users\Infinite\.m2\repository\org\apache\logging\log4j\log4j-api\2.6\log4j-api-2.6.jar;C:\Users\Infinite\.m2\repository\org\apache\logging\log4j\log4j-core\2.6\log4j-core-2.6.jar;C:\Users\Infinite\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.8.5\jackson-databind-2.8.5.jar;C:\Users\Infinite\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.8.5\jackson-core-2.8.5.jar;C:\Users\Infinite\.m2\repository\velocity-tools\velocity-tools\1.4\velocity-tools-1.4.jar;C:\Users\Infinite\.m2\repository\joda-time\joda-time\2.9.6\joda-time-2.9.6.jar;C:\Users\Infinite\.m2\repository\net\lingala\zip4j\zip4j\1.3.2\zip4j-1.3.2.jar;C:\Users\Infinite\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.24\plexus-utils-3.0.24.jar;C:\Users\Infinite\.m2\repository\org\jsoup\jsoup\1.10.1\jsoup-1.10.1.jar;C:\Users\Infinite\.m2\repository\com\googlecode\owasp-java-html-sanitizer\owasp-java-html-sanitizer\20160924.1\owasp-java-html-sanitizer-20160924.1.jar;C:\Users\Infinite\.m2\repository\com\aventstack\extentreports\3.1.2\extentreports-3.1.2.jar;C:\Users\Infinite\.m2\repository\org\freemarker\freemarker\2.3.23\freemarker-2.3.23.jar;C:\Users\Infinite\.m2\repository\org\mongodb\mongodb-driver\3.3.0\mongodb-driver-3.3.0.jar;C:\Users\Infinite\.m2\repository\org\mongodb\bson\3.3.0\bson-3.3.0.jar;C:\Users\Infinite\.m2\repository\org\mongodb\mongodb-driver-core\3.3.0\mongodb-driver-core-3.3.0.jar;C:\Users\Infinite\.m2\repository\org\reflections\reflections\0.9.10\reflections-0.9.10.jar;C:\Users\Infinite\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar;C:\Users\Infinite\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar;C:\Users\Infinite\.m2\repository\org\testng\testng\6.11\testng-6.11.jar;C:\Users\Infinite\.m2\repository\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;C:\Users\Infinite\.m2\repository\org\im4java\im4java\1.4.0\im4java-1.4.0.jar;C:\Users\Infinite\.m2\repository\info\cukes\cucumber-junit\1.2.4\cucumber-junit-1.2.4.jar;C:\Users\Infinite\.m2\repository\info\cukes\cucumber-core\1.2.4\cucumber-core-1.2.4.jar;C:\Users\Infinite\.m2\repository\info\cukes\cucumber-html\0.2.3\cucumber-html-0.2.3.jar;C:\Users\Infinite\.m2\repository\info\cukes\cucumber-jvm-deps\1.0.5\cucumber-jvm-deps-1.0.5.jar;C:\Users\Infinite\.m2\repository\info\cukes\gherkin\2.12.2\gherkin-2.12.2.jar;C:\Users\Infinite\.m2\repository\info\cukes\cucumber-java\1.2.4\cucumber-java-1.2.4.jar;C:\Users\Infinite\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\Infinite\.m2\repository\info\cukes\cucumber-testng\1.2.4\cucumber-testng-1.2.4.jar;C:\Users\Infinite\.m2\repository\com\madgag\animated-gif-lib\1.2\animated-gif-lib-1.2.jar;C:\Users\Infinite\.m2\repository\com\github\lalyos\jfiglet\0.0.7\jfiglet-0.0.7.jar;C:\Users\Infinite\.m2\repository\com\beust\jcommander\1.69\jcommander-1.69.jar;C:\Users\Infinite\.m2\repository\com\github\appiumtestdistribution\devicemanager\2.2\devicemanager-2.2.jar;C:\Users\Infinite\.m2\repository\com\github\yunusmete\stf\openstf-java-client\1.0\openstf-java-client-1.0.jar;C:\Users\Infinite\.m2\repository\com\squareup\retrofit\retrofit\1.9.0\retrofit-1.9.0.jar;C:\Users\Infinite\.m2\repository\com\squareup\okhttp3\okhttp\3.9.1\okhttp-3.9.1.jar;C:\Users\Infinite\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar;C:\Users\Infinite\.m2\repository\org\json\json\20171018\json-20171018.jar;C:\Users\Infinite\.m2\repository\org\everit\json\org.everit.json.schema\1.5.1\org.everit.json.schema-1.5.1.jar;C:\Users\Infinite\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Infinite\.m2\repository\com\googlecode\json-simple\json-simple\1.1\json-simple-1.1.jar;C:\Users\Infinite\.m2\repository\com\vimalselvam\cucumber-extentsreport\2.0.5\cucumber-extentsreport-2.0.5.jar;C:\Users\Infinite\.m2\repository\com\oracle\ojdbc6\11.2.0.4\ojdbc6-11.2.0.4.jar;C:\Users\Infinite\.m2\repository\com\jayway\restassured\rest-assured\2.9.0\rest-assured-2.9.0.jar;C:\Users\Infinite\.m2\repository\org\codehaus\groovy\groovy\2.4.4\groovy-2.4.4.jar;C:\Users\Infinite\.m2\repository\org\codehaus\groovy\groovy-xml\2.4.4\groovy-xml-2.4.4.jar;C:\Users\Infinite\.m2\repository\org\apache\httpcomponents\httpclient\4.5.1\httpclient-4.5.1.jar;C:\Users\Infinite\.m2\repository\org\apache\httpcomponents\httpcore\4.4.3\httpcore-4.4.3.jar;C:\Users\Infinite\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\Infinite\.m2\repository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\Infinite\.m2\repository\org\apache\httpcomponents\httpmime\4.5.1\httpmime-4.5.1.jar;C:\Users\Infinite\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Infinite\.m2\repository\org\hamcrest\hamcrest-library\1.3\hamcrest-library-1.3.jar;C:\Users\Infinite\.m2\repository\org\ccil\cowan\tagsoup\tagsoup\1.2.1\tagsoup-1.2.1.jar;C:\Users\Infinite\.m2\repository\com\jayway\restassured\json-path\2.9.0\json-path-2.9.0.jar;C:\Users\Infinite\.m2\repository\org\codehaus\groovy\groovy-json\2.4.4\groovy-json-2.4.4.jar;C:\Users\Infinite\.m2\repository\com\jayway\restassured\rest-assured-common\2.9.0\rest-assured-common-2.9.0.jar;C:\Users\Infinite\.m2\repository\com\jayway\restassured\xml-path\2.9.0\xml-path-2.9.0.jar;C:\Users\Infinite\.m2\repository\javax\persistence\javax.persistence-api\2.2\javax.persistence-api-2.2.jar;C:\Users\Infinite\.m2\repository\org\hamcrest\hamcrest-all\1.3\hamcrest-all-1.3.jar;C:\Users\Infinite\.m2\repository\com\google\code\gson\gson\2.6.2\gson-2.6.2.jar;C:\Users\Infinite\.m2\repository\com\jayway\restassured\json-schema-validator\2.2.0\json-schema-validator-2.2.0.jar;C:\Users\Infinite\.m2\repository\com\github\fge\json-schema-validator\2.1.7\json-schema-validator-2.1.7.jar;C:\Users\Infinite\.m2\repository\com\googlecode\libphonenumber\libphonenumber\5.6\libphonenumber-5.6.jar;C:\Users\Infinite\.m2\repository\com\github\fge\json-schema-core\1.1.8\json-schema-core-1.1.8.jar;C:\Users\Infinite\.m2\repository\com\github\fge\uri-template\0.7\uri-template-0.7.jar;C:\Users\Infinite\.m2\repository\com\github\fge\msg-simple\0.9\msg-simple-0.9.jar;C:\Users\Infinite\.m2\repository\com\github\fge\btf\1.0\btf-1.0.jar;C:\Users\Infinite\.m2\repository\com\github\fge\jackson-coreutils\1.4\jackson-coreutils-1.4.jar;C:\Users\Infinite\.m2\repository\org\mozilla\rhino\1.7R4\rhino-1.7R4.jar;C:\Users\Infinite\.m2\repository\com\google\inject\guice\3.0\guice-3.0.jar;C:\Users\Infinite\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\Infinite\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\Infinite\.m2\repository\javax\mail\mailapi\1.4.3\mailapi-1.4.3.jar;C:\Users\Infinite\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\plugins\testng\lib\jcommander.jar" org.testng.RemoteTestNGStarter -usedefaultlisteners false -socket22978 @w@C:\Users\Infinite\AppData\Local\Temp\idea_working_dirs_testng1.tmp -temp C:\Users\Infinite\AppData\Local\Temp\idea_testng1.tmp
OUTPUT DIRECTORY :G:\test\PageObjectPatternAppium-master\target
     _  _       _          _  _             _         
  __| |(_) ___ | |_  _ __ (_)| |__   _   _ | |_   ___ 
 / _` || |/ __|| __|| '__|| || '_ \ | | | || __| / _ \
| (_| || |\__ \| |_ | |   | || |_) || |_| || |_ |  __/
 \__,_||_||___/ \__||_|   |_||_.__/  \__,_| \__| \___|
                                                      

***************************************************

Total Number of devices detected::2

***************************************************

starting running tests in threads
Dec 06, 2018 1:44:11 AM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...

**************************************************************************

Starting Appium Server on Localhost......
**************************************************************************

Picking Default Path for AppiumServiceBuilder
[Appium] Welcome to Appium v1.10.0
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 16551
[Appium]   logFile: G:\test\PageObjectPatternAppium-master\target\appiumlogs\appium_logs.txt
[Appium]   relaxedSecurityEnabled: true
[Appium] Appium REST http interface listener started on 127.0.0.1:16551
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.10.0"}}
[HTTP] <-- GET /wd/hub/status 200 16 ms - 68
[HTTP] 
**************************************************************************

Appium Server Started at......http://127.0.0.1:16551/wd/hub
**************************************************************************

Dec 06, 2018 1:44:17 AM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.utils.AppiumDevice@6f458994 for Execution

0 Scenarios
0 Steps
0m0.000s

FAILED: feature(Verifying API Response of getTlogger Service against TT UI for CP region)
        Runs Cucumber Feature
java.lang.NullPointerException
	at com.cucumber.listener.CucumberListener.step(CucumberListener.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy17.step(Unknown Source)
	at cucumber.runtime.model.StepContainer.format(StepContainer.java:33)
	at cucumber.runtime.model.CucumberScenarioOutline.formatOutlineScenario(CucumberScenarioOutline.java:52)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:41)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

===============================================
    TestNG Test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
TestNG Forum
Total tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

Process finished with exit code 0

_Originally posted by @KumarKola in https://github.com/AppiumTestDistribution/AppiumTestDistribution/issues/415#issuecomment-444766782_

**Comment by saikrishna321** [comment]
sorry, @KumarKola haven't got time to work on this. Happy to review PR if u can help on this
