### ISSUE TITLE
Not able to execute all the test cases, only first test case is executing successfully in the suite

### ISSUE THREAD

**Issue by amargvn** [AppiumTestDistribution/AppiumTestDistribution#423]
I have 9 test cases, in the suite, while running the test cases using runner.java - Only first test case is executing successfully, rest of them all are failing. 

**Note**: If i comment the test case #1 and run the suite also the first test case only executing successfully.
please help me to resolving the issue.

Note: I am executing on Windows machine.

**Comment by saikrishna321** [comment]
@amargvn can u pls provide us the error logs and also which version you are using? Is the runner TestNG or Cucumber ?

**Comment by saikrishna321** [comment]
closing as inactive
