### ISSUE TITLE
Have a "dry-run" type of capability

### ISSUE THREAD

**Issue by anandbagmar** [AppiumTestDistribution/AppiumTestDistribution#427]
It would be nice to have a dry-run type of capability - that just lists / shows which tests would be executed, which devices are available, etc. Maybe this could also create a basic report to give an indication how the end-results would look like

**Comment by saikrishna321** [comment]
> that just lists / shows which tests would be executed

I believe you want to know the tests which are tagged under specific group

> which devices are available

This would be the connected devices or the devices the test would run 

> Maybe this could also create a basic report to give an indication how the end-results would look like

This is not possible because we dont know which test will be executed on which device

**Comment by anandbagmar** [comment]
its about which devices are available, NOT which test would run on which device
similarly in the report - its just test run metadata - not actual report

**Comment by saikrishna321** [comment]
@anandbagmar @SrinivasanTarget To start of i'm going to display in commandline and can look a report iteratively.

command: Platform=android mvn clean -Dtest=Runner test -Ddry-run=true

This is will results a build failure as i'm calling system.exit(0) to terminate the execution.

<img width="718" alt="screen shot 2018-12-22 at 4 20 06 pm" src="https://user-images.githubusercontent.com/4045041/50373463-8788bf80-0605-11e9-9f4a-29bcbc694de7.png">
