### ISSUE TITLE
Unable to generate Extent Report if runner is 'distribute'

### ISSUE THREAD

**Issue by Zarmeena** [AppiumTestDistribution/AppiumTestDistribution#440]
It is for the previous version of ATD in which report portal is not integrated

**Comment by SrinivasanTarget** [comment]
@Zarmeena We have taken off the Extent Report support from our framework already. If you could build one locally at your end, you can add a custom listener to config.properties.

**Comment by Zarmeena** [comment]
We will try implementing a custom listener  and get back to you.
