### ISSUE TITLE
Distribute mode is working correctly with cucumber in real devices

### ISSUE THREAD

**Issue by KumarKola** [AppiumTestDistribution/AppiumTestDistribution#441]
Hi SaiKrishna@saikrishna321 and @SrinivasanTarget i am trying to run test cases in distributed mode in real devices.. my android app is invoking in both devices but test cases are executing only one one device..

exapmple: I have 3 test cases set for distributed mode but all 3 cases are kept in pool for device 1 i dont see any activity in device 2 it just invoked the app.

**Comment by saikrishna321** [comment]
@KumarKola can u pls the logs and also which version of ATD are u using

**Comment by KumarKola** [comment]
> @KumarKola can u pls the logs and also which version of ATD are u using

Its working fine, it was config issue in my system
