### ISSUE TITLE
How to Integrate the appium test distribution project in jenkins ?

### ISSUE THREAD

**Issue by KumarKola** [AppiumTestDistribution/AppiumTestDistribution#445]
Hi @saikrishna321  and @SrinivasanTarget  I would like to add the pageObjectPattern project into CICD pipeline, Is there any specific setup that needs to be configured ? could you provide the steps if you have any. Thank you.

**Comment by saikrishna321** [comment]
@KumarKola Nope, ATD will run like any other test in CI. What have you tried so far?

**Comment by KumarKola** [comment]
> @KumarKola Nope, ATD will run like any other test in CI. What have you tried so far?

I tried usual way by creating a freestyle project and providing this command---->mvn validate && Platform="android" mvn clean -Dtest=RunnerCukes test. But I see this error in the console------>'Platform' is not recognized as an internal or external command,
operable program or batch file.


I have given this code in my pom.xml

![image](https://user-images.githubusercontent.com/45509929/55212039-b98d5d00-51c4-11e9-9d9d-78ea6705f807.png)

**Comment by saikrishna321** [comment]
Yah, i think u need to set Platform as env in your jenkins

**Comment by KumarKola** [comment]
I tried that but seeing the same error---'Platform' is not recognized as an internal or external command,
operable program or batch file.


when i use this command--->mvn clean test -Dtest=RunnerCukes test -DPlatform=android
I am seeing this error... Running com.appium.steps.RunnerCukes
Configuring TestNG with: TestNG652Configurator
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.573 sec <<< FAILURE! - in com.appium.steps.RunnerCukes
testCukesRunner(com.appium.steps.RunnerCukes)  Time elapsed: 0.05 sec  <<< FAILURE!
java.lang.IllegalArgumentException: Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test
        at com.appium.schema.CapabilitySchemaValidator.isPlatformInEnv(CapabilitySchemaValidator.java:64)
        at com.appium.schema.CapabilitySchemaValidator.validateCapabilitySchema(CapabilitySchemaValidator.java:22)
        at com.appium.manager.ATDRunner.<init>(ATDRunner.java:44)
        at com.appium.steps.RunnerCukes.testCukesRunner(RunnerCukes.java:13)


Results :

Failed tests:
  RunnerCukes.testCukesRunner:13 » IllegalArgument Please execute with Platform ...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by MummanaSubramanya** [comment]
@saikrishna321 worked !!

**Comment by saikrishna321** [comment]
Would b great if you can post the solution might help others

**Comment by MummanaSubramanya** [comment]
In macbook testsuite executes with out any issue but the issue is with windows environment.
To run on windows 
We should add the property in maven surefire plugin:

            <configuration>
                <properties>
                    <Platform>${Platform}</Platform>
                </properties>
            </configuration>

 and then run below commands as 
1) setx -m Platform "android" 
2) mvn clean test -Dtest=Runner test -DPlatform=android

**Comment by MummanaSubramanya** [comment]
Would be great if you could update README.md for windows :)

**Comment by KumarKola** [comment]
@mummanaSubramanya could you please suggest me how you connected your device to Jenkins which is running on AWS instance?

**Comment by MummanaSubramanya** [comment]
well we have local Jenkins instance so it was easy :). 

I understand your concern. I have an idea for you:

1) connect the devices to your local machine and assign public IP to it. Take help of your IT team.
2) follow this https://github.com/AppiumTestDistribution/AppiumTestDistribution/wiki/Remote-Execution in your project and in the capabilities mention the public Ip of your local machine.
3) Build your project in your Jenkins AWS instance then you can see testcase executions in your local.

**Comment by KumarKola** [comment]
@mummanaSumbramanya where should I run the appiumremote manager jar? In local machine?

**Comment by saikrishna321** [comment]
Are the devices connected to the machine which u have access ?

**Comment by KumarKola** [comment]
I have a machine sitting in my local and I will connect devices to that system. But Jenkins is on AWS so the part I am not sure is how to connect my local machine to Jenkins, which will execute Jenkins command and run cases on tablet devices.

**Comment by saikrishna321** [comment]
Can your AWS Jenkins ping your local?Is there any tunnel open

**Comment by saikrishna321** [comment]
@MummanaSubramanya Do you mind helping to update the readMe?

**Comment by KumarKola** [comment]
> Can your AWS Jenkins ping your local?Is there any tunnel open

@saikrishna321  No configuration is present for that. is there any alternative solution for that? If i use emulators will that be a easier to integrate it with jenkins ?

**Comment by saikrishna321** [comment]
I'm afraid not!!

**Comment by KumarKola** [comment]
Ok, so then there's no other way to integrate with Jenkins! ?

**Comment by saikrishna321** [comment]
You can integrate with Jenkins for sure. In your case either the devices should be hooked to Jenkins or emulators running in Jenkins instance or ur Jenkins machine be able to ping ur system where the devices are connected.

**Comment by KumarKola** [comment]
@saikrishna321 I have configured jnlp node setup now I am able to get the pings from Jenkins. Could you please suggest me how to proceed further. Thanks.
