### ISSUE TITLE
Execution Time of Tests on both Android and iOS

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#447]
Is there any difference between the execution time of a test case on ios and the execution time of the same test case on android?

On my dashboard, I notice that iOS takes a longer time to execute the same test case than on android. It takes double the time...

**Comment by saikrishna321** [comment]
Yes, iOS test are slower than Android. Depends on many facts like what locator strategy your using if it's xpath for sure that's gone by very slow or how large your app Dom is. 

This is more a Appium question
