### ISSUE TITLE
Retry Count Issue

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#449]
Suppose I am running 8 test scripts and I want to run multiple iterations (say 2)of the same 8 test scripts. This means totally 16 test flows.

Android: It shows 8 skipped tests and the remaining 8 tests.
Why does it skip the 8 tests rather than re-running the 8 tests?

iOS: It does not work. It only runs the 8 test scripts and does not re-iterate.

What could be the issue? Should I add any parameters to the command while execution?

In config.properties, I added the following:
MAX_RETRY_COUNT = 2

**Comment by saikrishna321** [comment]
RETRY only works when a test fails. It retries the failed test

**Comment by rameshgit96** [comment]
I see. Is there a way to run all the tests over multiple iterations even if all tests pass? Is there a parameter that I can add to config.properties for this?

**Comment by saikrishna321** [comment]
No not within the framework.
