### ISSUE TITLE
Testng annotations @Before and @After annotations not invoked for @Test

### ISSUE THREAD

**Issue by narmadha956** [AppiumTestDistribution/AppiumTestDistribution#450]
Any of the TestNg annotations are not getting invoked from Tests file.

Example Used:
    @AfterClass
    public void testing()
    {
                 System.out.print("After Class");
    }

https://gist.github.com/narmadha956/11039ed2efa772e89f07973d38e4bee9

**Comment by narmadha956** [comment]
@saikrishna321 @VinayakaMayura  FYI

**Comment by saikrishna321** [comment]
Can u show the implementation ?

**Comment by narmadha956** [comment]
Implementation is just a print command in @AfterClass like in the example above. The method is not getting invoked. Only @Test methods are invoked. Tried multiple @After and @Before

**Comment by narmadha956** [comment]
My test cases were in group, so @AfterGroups worked, others were not supposed to work.
