### ISSUE TITLE
Running From Jenkins

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#458]
How can we run this ATD project from Jenkins?

**Comment by saikrishna321** [comment]
@rameshgit96 Nothing different from the way you run from commandline. What have you tried till now ?

**Comment by rameshgit96** [comment]
I am getting an exception:
java.io.IOException: Cannot run program "appium": error=2, No such file or directory

Parallel 
No Devices Connected

**Comment by saikrishna321** [comment]
which means Appium is not installed nor set in path

**Comment by rameshgit96** [comment]
By that do you mean that Appium must be set as anOS environment variable?

**Comment by saikrishna321** [comment]
I mean is appium installed globally in jenkins ?

**Comment by rameshgit96** [comment]
Yes, I think what you mean is if appium is installed globally in the same machine as the one in which Jenkins exists. If that's the case, then yes.

**Comment by saikrishna321** [comment]
Can you run command _appium_ in jenkins and paste the output

**Comment by rameshgit96** [comment]
/bin/sh -c appium
/bin/sh: appium: command not found
Build step 'Execute shell' marked build as failure

**Comment by saikrishna321** [comment]
/bin/sh: appium: command not found 

So appium is not installed on the machine or not set to PATH

**Comment by rameshgit96** [comment]
When I type in "appium -v" in the machine's command line, it shows the appium version. Is there a specific path for a variable "appium"?
