### ISSUE TITLE
Running Tests On Specific Devices

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#477]
How can I run tests on specific devices by specifying the UDID's?

**Comment by saikrishna321** [comment]
You can set udids in env comma separated as UDIDS="udid2,udid2"1

**Comment by rameshgit96** [comment]
This works for Android as well, correct? By specifying the IMEI number or serial number? Would this be the right order?
CONFIG_FILE="config2.properties" Platform="android" UDIDS="<IMEI/Serial#>" mvn clean -Dtest=Runner test

It builds success but doesn't run any tests. Would that be the right format?

**Comment by saikrishna321** [comment]
it's the serial number and it works for Android as well

**Comment by rameshgit96** [comment]
Ok, I entered the above command. However, it runs tests on all the devices. I tried placing UDIDS="udid" before CONFIG_FILE, after CONFIG_FILE, before mvn.

However, it doesn't work.

**Comment by saikrishna321** [comment]
@rameshgit96 Sorry, my bad it should be _udids_

`CONFIG_FILE="config2.properties" Platform="android" udids="<Serial>" mvn clean -Dtest=Runner test`

**Comment by rameshgit96** [comment]
Thank you. It worked.
