### ISSUE TITLE
Runtime - OutOfMemoryError

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#487]
Exception in thread "ThreadedStreamConsumer" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.maven.plugin.surefire.booterExcepticon in thread "Thread-lient.output.ForkClien2" java.lang.OutO
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ThreadedStreamConsumer"
fMemoryError: GC overhead limit exceeded

**Comment by rameshgit96** [comment]
I am getting the above Exception when I am running the tests on 2 devices in parallel. I have run 48 tests on both tests in parallel. Please let me know if you need more information.

**Comment by saikrishna321** [comment]
Can u pls post full logs and what happens when this exception is hit ?

**Comment by rameshgit96** [comment]
I have edited my issue with the most recent exception. What happens is that the test flows stop on all 6 devices. I am running 42 tests in parallel on 6 android devices. Is there a way to resolve this by increasing the heap size, etc?

**Comment by saikrishna321** [comment]
https://stackoverflow.com/questions/37335/how-to-deal-with-java-lang-outofmemoryerror-java-heap-space-error
