### ISSUE TITLE
ADB Logs Missing

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#493]
When I run a test on 2 devices, a adb logs (.txt) file for  both devices is created. However, for one of the .txt files for a device is empty.

So, basically, only the adb logs for one out of the 2 devices exists. The other file for the other device is empty.

**Comment by rameshgit96** [comment]
Can someone please look into this? Thank you.

**Comment by zarashima** [comment]
Meet the same issue from my side

**Comment by saikrishna321** [comment]
Please try with latest master commit. 

_app_ contract has been changed for android object.

https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/master/caps/capabilities.json#L8-L9


```

	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependency>
	    <groupId>com.github.AppiumTestDistribution</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>8f1e2e1156</version>
	</dependency>

```

**Comment by rameshgit96** [comment]
Sorry for the late reply. I'll try this and get back to you

**Comment by rameshgit96** [comment]
Yes, this worked with <version>c5c657c32f</version> 
successfully.
