### ISSUE TITLE
Running tests on Chrome and Safari

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#499]
What are the requirements to run appium tests on safari and chrome in terms of changes to capabilities.json, config.properties, etc.?

**Comment by saikrishna321** [comment]
Just set browser and capability

**Comment by zarashima** [comment]
@saikrishna321 : Can you elaborate more about this?

**Comment by saikrishna321** [comment]
Set _browserName_ capability to chrome or safari, if it's safari real device make sure u set IWDP capability to true

**Comment by rameshgit96** [comment]
Thanks Sai. I simply took out "app" capability and inserted "browserName": "Chrome". It worked. However, I will try on Safari and confirm that it works.

**Comment by zarashima** [comment]
Thanks got it worked. So in case I want to change desired capabilities in run-time, is it possible to change capabilities directly from code?

**Comment by saikrishna321** [comment]
U can't update capability on runtime
