### ISSUE TITLE
How to set capabilities for multiple Android devices

### ISSUE THREAD

**Issue by zarashima** [AppiumTestDistribution/AppiumTestDistribution#501]
How to set capabilities for multiple Android devices in `capabilities.json` file?

**Comment by saikrishna321** [comment]
You don't have to set for multiple devices. The frameworks will create multiple sessions with different UDID on run time

**Comment by zarashima** [comment]
@saikrishna321 : Thanks, it's my mistake not reading the user guide carefully.
