### ISSUE TITLE
Issue when executing on cloud devices

### ISSUE THREAD

**Issue by zarashima** [AppiumTestDistribution/AppiumTestDistribution#504]
So far I've made correct configurations to execute tests on Sauce based on this [guide](https://github.com/AppiumTestDistribution/AppiumTestDistribution/wiki/Configure-test-for-Cloud-Sauce), and when calling this command:

`CLOUD_USER=myuser CLOUD_KEY=mypass mvn clean -Dtest=Runner test`

The following error is generated:
```
java.lang.IllegalArgumentException: Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test
        at com.appium.schema.CapabilitySchemaValidator.isPlatformInEnv(CapabilitySchemaValidator.java:64)
        at com.appium.schema.CapabilitySchemaValidator.validateCapabilitySchema(CapabilitySchemaValidator.java:22)
        at com.appium.manager.ATDRunner.<init>(ATDRunner.java:44)
        at com.appium.tests.Runner.testRunner(Runner.java:13)
```

Is there anything wrong from my side or from the given document?

**Comment by saikrishna321** [comment]
You need to set Platform if ur running android, iOS or both as Platform=android or Platform=iOS or Platform=both
```
CLOUD_USER=myuser CLOUD_KEY=mypass Platform=both mvn clean -Dtest=Runner test
```

**Comment by WasiqB** [comment]
@saikrishna321 , we can make **Android** as the default platform property which will be picked if platform environment variable is not provided. What's your thoughts on this?

**Comment by saikrishna321** [comment]
Yes, we can default android provided it's windows machine

**Comment by saikrishna321** [comment]
closing as the original issue is resolved
