### ISSUE TITLE
Getting the url of the reportportal launch from test execution

### ISSUE THREAD

**Issue by anandbagmar** [AppiumTestDistribution/AppiumTestDistribution#505]
ATD should be able to provide the link of the launch added in reportportal for the test execution

**Comment by SrinivasanTarget** [comment]
Didn't get what URL are you expecting to be exposed? Can you please add more details?

**Comment by anandbagmar** [comment]
Sorry was vague. Let me elaborate on this:
- when we run a suite of tests using ATD, the reports are generated within a "new launch" in reportportal.io
- as there could be many such suites running (from CI / local), there will be many "launch" reports in reportportal
- It would help to know under which "launch", and where, can I find my suite results. 

See the below screenshot for ex:
<img width="931" alt="ReportPortal-launches" src="https://user-images.githubusercontent.com/502964/60483934-3db81a80-9cb5-11e9-9d2c-3831270e63ff.png">

So, it would be nice to see in the result output, or somewhere, a link of where my test suite execution reports are in reportportal. - ex: the launch of my interest is launch no 114

**Comment by zarashima** [comment]
You can combine multiple parameters from ReportPortal itself to build generated launch URL. They expose many properties and can be retrieved in a form of `System.getProperty(rp.property)` for customization, refer here:
https://github.com/reportportal/reportportal/issues/247

So applied in Java it will be:

```
String getLaunchUrl() {
 return String.format("http://%s/ui/%s/launches/all/%s",System.getProperty("rp.endpoint"),System.getProperty("rp.project"),System.getProperty("rp.launch.id");
}
```

**Comment by anandbagmar** [comment]
Thanks @zarashima - that worked - well almost - I had to make slight tweaks - as in my case the rp.endpoint and rp.project did not come up as system properties. But other than that, this worked great.

**Comment by saikrishna321** [comment]
PR merged to master. https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/511
