### ISSUE TITLE
Issue After Changing to Java-Client-7.0.0

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#508]
When I change to Java - Client - 7.0.0,
I get an exception after running the test from command line: java.lang.NoSuchFieldError: RELAXED_SECURITY

**Comment by saikrishna321** [comment]
@rameshgit96 Looks like u still the old dependencies in your project space. Please clear cache and restart IDE and make sure you have the latest java-client
