### ISSUE TITLE
How to configure for execution of a specific test method?

### ISSUE THREAD

**Issue by zarashima** [AppiumTestDistribution/AppiumTestDistribution#509]
Hi, 

Based on this [guide](https://github.com/AppiumTestDistribution/AppiumTestDistribution/wiki/Configure-tests-for-TestNG), so in case I want to execute only a specific test method in a test package, then how can I define it?

Thanks

**Comment by saikrishna321** [comment]
Currently ATD does not support this. Can add it as feature request

**Comment by zarashima** [comment]
@saikrishna321 : Thanks for your information. Another question sound unrelated to this but how can I specify test execution order as well? Example I have the following code:
```
 ATDRunner parallelThread = new ATDRunner();
 List<String> test = new ArrayList<String>();
 test.add("MySetupTest");
 test.add("NormalTest");
 parallelThread.runner("my.package.test", test);
```

Upon execution, the tests in "NormalTest" package is always executed first due to its package's name ordering from the list of added tests I believe so. How can I let "MySetupTest" always start first from ATD?

Regards

**Comment by saikrishna321** [comment]
I'm afraid you can't do that!! Looking at your file name as setup Test are you running some test data setup ?

**Comment by zarashima** [comment]
Just an example. I can name it to be a different one, but then there will be cases the test's name is not meaningful.

**Comment by saikrishna321** [comment]
To run specific methods I would recommend tag the methods with groups and execute INCLUDE_GROUPS="test1,test2" mvn clean -Dtest=Runner test

**Comment by zarashima** [comment]
Thanks . Made a slight tweak to call our customized mvn commands from my project to adapt with this for now. Hoping for this enhancement soon :)
