### ISSUE TITLE
Unable to map elements from IDE

### ISSUE THREAD

**Issue by yair22** [AppiumTestDistribution/AppiumTestDistribution#516]
I'm using the page object pattern to test my app.
Everything was working fine until I updated Appium to a version above 1.9.
Ever since the driver.getPageSource() returns a "Not implemented" exception and i'm unable to access any of the elements in the app - The elements are accessible via the inspector.

**Comment by saikrishna321** [comment]
How is this issue with ATD framework ?

**Comment by saikrishna321** [comment]
Closing as not ATD issue
