### ISSUE TITLE
Not able to generate Cucumber overview html report in project directory

### ISSUE THREAD

**Issue by KumarKola** [AppiumTestDistribution/AppiumTestDistribution#522]
Hi @saikrishna321  I am able generate cucumber.json files and cucumber html files individually but i am not able to get the overview report.html. 

![image](https://user-images.githubusercontent.com/45509929/61550373-44b68b00-aa20-11e9-8cb4-f595643343fb.png)

This the POM.XML

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.pagepattern.appium</groupId>
    <artifactId>5g_home_install</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <properties>
        <testTag>@Smoke</testTag>
    </properties>

    <dependencies>

      

        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.6.2</version>
        </dependency>
        
        <dependency>
            <groupId>ojdbc6</groupId>
            <artifactId>ojdbc6</artifactId>
            <version>11.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.saikrishna321</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>10.0.1</version>
    </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>LATEST</version>
        </dependency>

        
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>3.0.0</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.9.0</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.8</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
        </dependency>
        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>4.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.17</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.vimalselvam</groupId>
            <artifactId>cucumber-extentsreport</artifactId>
            <version>3.1.1</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>

                 
                </configuration>

            </plugin>
            <plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>4.2.0</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            
                            <outputDirectory>src/test/java</outputDirectory>
                            
                            <glue>com.appium.steps</glue>
                            <featuresDirectory>src/test/resources/features</featuresDirectory>
                            <cucumberOutputDir>target/cucumber-report-html</cucumberOutputDir>
                            <format>pretty</format>
                            <strict>true</strict>
                            <monochrome>true</monochrome>
                            <tags>
                                <tag>@${testTag}</tag>

                            </tags>

                            <namingScheme>simple</namingScheme>
                            
                            <namingPattern>Parallel{c}IT</namingPattern>
                            <parallelScheme>SCENARIO</parallelScheme>
                            <packageName>output</packageName>
                            <useTestNG>true</useTestNG>
                            <plugins>
                                <plugin>
                                    <name>com.cucumber.listener.CucumberListener</name>
                                </plugin>
                                <plugin>
                                <name>json</name>
                                <extension>json</extension>
                                <outputDirectory>target/reports</outputDirectory>
                            </plugin>
                                <plugin>
                                    <name>html</name>
                                    <extension>html</extension>
                                    <outputDirectory>target/cucumber-report-html</outputDirectory>
                                </plugin>

                            </plugins>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                        </manifest>
                    </archive>
                </configuration>

            </plugin>

        </plugins>

    </build>
</project>

**Comment by saikrishna321** [comment]
https://github.com/damianszczepanik/cucumber-reporting#usage 

You can write a simple merge code in your Runner.java class after the execution

**Comment by KumarKola** [comment]
Hi @saikrishna321  thanks for the help, able to do that now Closing this issue.
