### ISSUE TITLE
Integration with pCloudy.com

### ISSUE THREAD

**Issue by shibupanda** [AppiumTestDistribution/AppiumTestDistribution#532]
Assigned my self as I will refactor our(Pcloudy design) to support ATD.
@saikrishna321 could you please mark this as an enhancement. Thanks

**Comment by saikrishna321** [comment]
Thanks for supporting @shibupanda

**Comment by saikrishna321** [comment]
@shibupanda Any help needed in this space?

**Comment by shibupanda** [comment]
Hi @saikrishna321 Sorry for inconvenience.
I have already refactored pCloudy design I wait for the stabilisation.
Now I think need to add those capability.

I need your help here as we are exposing username and apikey also as a capability.
So if we'll use `CLOUD_USER=browserstack_user CLOUD_KEY=browserstack_password mvn clean -Dtest=Runner test`  this way  then in pCloudy case this value needs to be passed as a value.

If somehow I can connect with the team we can integrate soon.

**Comment by saikrishna321** [comment]
@shibupanda I'm happy to help. Can we connect over zoom?

**Comment by anandbagmar** [comment]
Hey @shibupanda , were you able to get this working?

**Comment by saikrishna321** [comment]
@shibupanda Any updates on this?

**Comment by shibupanda** [comment]
@saikrishna321 Sorry for late. Was deployed in some other projects. Now I came back will take this in current sprint for sure. I will connect you in Appium slack if any help required.
