### ISSUE TITLE
ExtentReport.html not created 

### ISSUE THREAD

**Issue by yair22** [AppiumTestDistribution/AppiumTestDistribution#534]
Running TestNg tests and the target folder is filled but no report is generated.
Is testNG only supposed to run with the reportPortal?

**Comment by saikrishna321** [comment]
@yair22 Yes, we currently only support report portal. Do you any downside of using RP and prefer extent-reports?

**Comment by yair22** [comment]
@saikrishna321 Yes, we are already implementing an older version of the ATD using extent report for Android combining it with other resources in our environment. We would have liked to use the current ATD under the same environment for iOS producing the same sort of reports. Considering that RP also requires a docker env on top on what we already have, the integration to our existing environment will be very time consuming.

**Comment by saikrishna321** [comment]
@yair22 Can you please show the extent report sample which you are using with ATD version?


@SrinivasanTarget

**Comment by yair22** [comment]
We are using ATD version 7.03 and extent reports version 3.1.2. 
Not sure what you mean by report sample, do you mean a screen shot of one of our reports?

**Comment by saikrishna321** [comment]
>> Do you mean a screen shot of one of our reports?

Yes

**Comment by yair22** [comment]
![Screen Shot 2019-08-21 at 12 08 06 (2)](https://user-images.githubusercontent.com/52748208/63418939-93cf5180-c40c-11e9-9b08-22d77252bd6e.png)

**Comment by yair22** [comment]
![Screen Shot 2019-08-21 at 12 08 41](https://user-images.githubusercontent.com/52748208/63419003-b1042000-c40c-11e9-851f-a12e54326b1c.png)

**Comment by yair22** [comment]
![Screen Shot 2019-08-21 at 12 15 21](https://user-images.githubusercontent.com/52748208/63419468-8b2b4b00-c40d-11e9-8d8a-4ca025d3821b.png)

**Comment by saikrishna321** [comment]
Expected: Create a ATD-Extent plugin to support this. As we currently support queueing of Listeners
