### ISSUE TITLE
Terminal hanging if the tests run for more than an hour

### ISSUE THREAD

**Issue by bhimudev** [AppiumTestDistribution/AppiumTestDistribution#555]
Hello, 

I have close to 60-70 tests in the project each test takes 4-5 mins to run, total time taken by the test to run completely is around 2.5-3 hrs. 

The tests are running fine when they are executed form the run configuration, but the test were executed form terminal using Platform=android mvn clean -Dtest=Runner test, the terminal hanging after the test were executed for around 50-60 min. 

Testes were executed with below environment 

OS : Mac OS 10.14.3
RAM : 64 GB DDR4
JAVA : 1.8
XCode - 10.3
Android emulator : API 27 with os 8.1.0
iOS Simulator with 12.1

**Comment by saikrishna321** [comment]
@bhimudev Maybe something to do with your machine cpu usage.
