### ISSUE TITLE
No Device Connected, couldn't fetch the devices connected and appium server is not starting

### ISSUE THREAD

**Issue by sri102info** [AppiumTestDistribution/AppiumTestDistribution#559]
I'm trying to configure the AppiumTestDistribution in my framework to support for Appium Server Management.

My Pom.xml:
`<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.6</maven.compiler.source>
		<maven.compiler.target>1.6</maven.compiler.target>
	</properties>
<dependencies>
		<dependency>
			<groupId>com.App</groupId>
			<artifactId>mobile-testframework</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>MobileAutomation</groupId>
			<artifactId>Pages</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>com.github.saikrishna321</groupId>
			<artifactId>AppiumTestDistribution</artifactId>
			<version>11.0.0</version>
		</dependency>
	</dependencies>`
Having two Test classes, namely Runner.java and LoginTest.java

Runner.java:
`
package Tests;

import com.appium.manager.ATDRunner;
import java.util.ArrayList;

import org.testng.annotations.Test;

public class Runner {
    @Test
    public void testApp() throws Exception {
        ATDRunner parallelThread = new ATDRunner();
        ArrayList<String> test = new ArrayList<String>();
        test.add("LoginTest");
        boolean runner = parallelThread.runner("Tests", test);
    }
}  

`

LoginTest.java: To check whether Driver generation is proper or not.
`public class LoginTest {
    LoginPage loginPage;
    public void setUp() {
        loginPage = new LoginPage(AppiumDriverManager.getDriver());
    }`

`Capabilities.json:
{
  "android": {
    "platformName": "android",
    "app": {
      "local": "./build/app-UAT-release-V1.1.6-09.apk"
    },
    "appPackage": "com.app.Sample",
    "appActivity": "com.MyActivity",
    "deviceName": "android",
    "automationName": "UIAutomator2",
    "noSign": true
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "appiumServerPath": "/usr/local/lib/node_modules/appium/build/lib/main.js"
    }
  ]
}`

config.properties:
`RUNNER=distribute
APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js
FRAMEWORK=testng`

Created a new Emulator via Android SDK and it is running
Android OS: Q
Device Name: Pixel 2
`mm-in-sridhar:~ sridhar$ adb devices
List of devices attached
emulator-5554	device`

But when I'm trying to run the Runner class with the below command,
Platform="android" mvn clean -Dtest=Runner test

I'm getting below message as No device connected.
`distribute
No Devices  Connected`

I'm not sure what went wrong and what I missed?

Could you help me out in fixing this issue?

**Comment by saikrishna321** [comment]
@sri102info I'm unable to reproduce this.

**Comment by saikrishna321** [comment]
Can you try with this repo - https://github.com/AppiumTestDistribution/PageObjectPatternAppium
