### ISSUE TITLE
Unable to generate Parallel**IT.java class automatically for executing Cucumber tests

### ISSUE THREAD

**Issue by Zarmeena** [AppiumTestDistribution/AppiumTestDistribution#564]
We are trying to invoke Cucumber feature files using: mvn clean -Dtest=RunnerCukes test -DPlatform=android, but the 'output' package is not getting refreshed. Initially it was working fine.

Version of AppiumTestDistribution jar used: 9.1.0

**Comment by saikrishna321** [comment]
@Zarmeena Thanks for reporting. Cucumber runner is currently broken and there is an open issue for this. I'm happy to review a PR

**Comment by Zarmeena** [comment]
Hi Sai, Could you try fixing this issue?
