### ISSUE TITLE
Can't run test as parallel

### ISSUE THREAD

**Issue by phoebusliang** [AppiumTestDistribution/AppiumTestDistribution#570]
Preparation:
1. Update the capabilities.json and update the hostMachines as:
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "appiumServerPath": "/usr/local/lib/node_modules/appium/build/lib/main.js",
      "simulators": [
        {
          "deviceName": "iPhone 11 Pro Max",
          "OS": "13.1"
        },
        {
          "deviceName": "iPhone 11 Pro",
          "OS": "13.1"
        }
      ]
    }
  ]
2. exec the command  "Platform="ios" mvn clean -Dtest=Runner test"

Results:
1. The test run successfully on these two devices as sequence one by one, not running as parallel

**Comment by saikrishna321** [comment]
Can you post the logs?

**Comment by phoebusliang** [comment]
[debug] [iOS] Deleting '/pathto/Logs'. Freeing 3.1M.
[debug] [iOS] Finished clearing log files
[debug] [IOSSimulatorLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1573570362201 (22:52:42 GMT+0800 (China Standard Time))
[debug] [W3C (407cedf8)] Received response: null
[debug] [W3C (407cedf8)] But deleting session, so not returning
[debug] [W3C (407cedf8)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/2xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx 200 1057 ms - 14
[HTTP]
Nov 12, 2019 10:52:42 PM com.appium.manager.DeviceAllocationManager freeDevice
INFO: DeAllocated Device 1xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx from execution list
Nov 12, 2019 10:52:42 PM com.context.SessionContext remove
INFO: Removing context for thread - 24
After DeviceId1xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
com.appium.executor.CustomeListener.afterInvocation() was invoked
PASSED: dragNDrop
        Platform: IOS UDID: 2xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx Name: iPhone 11 Pro Max Host: 127.0.0.1
PASSED: dragNDrop
        Platform: IOS UDID: 1xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx Name: iPhone 11 Pro Host: 127.0.0.1

===============================================
    ATDTest
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
ATDSuiteName
Total tests run: 2, Failures: 0, Skips: 0

**Comment by phoebusliang** [comment]
> Can you post the logs?

The logfile will be removed after finish running. It seems all tests passed but not running as parallel.

**Comment by saikrishna321** [comment]
Appium logs are should be stored in your target folder and complete logs should be printed after the run.
