### ISSUE TITLE
Parallel Execution on Android and IOS

### ISSUE THREAD

**Issue by pavanbachu06** [AppiumTestDistribution/AppiumTestDistribution#573]
Is it possible to execute a single test case in parallel on both iOS and Android connected devices? If so, I currently have a framework which is written on JUnit, what all do I need to modify so as to implement a parallel runner?

**Comment by saikrishna321** [comment]
@pavanbachu06 Yes, you can! ATD uses TestNg and not JUnit

**Comment by pavanbachu06** [comment]
Do I need to move my testing framework to testNG in order to use ATD?

**Comment by saikrishna321** [comment]
@pavanbachu06  Yes!!
