### ISSUE TITLE
Simultaneous App Launch - Real Devices

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#574]
Suppose I'm running my tests on 10 devices.

I notice that the app takes a certain amount of time to launch on one device compared to another. Is it possible for the framework to launch the app at the same time on all devices?

**Comment by saikrishna321** [comment]
@rameshgit96 ATD just sends the command to appium to create the driver instance. There can be multiple reasons for the difference in the launch of app btw devices like device slowness, adb

**Comment by rameshgit96** [comment]
I see. But when ATD sends the command to appium, is this a parallel or sequential process? I mean, suppose there are 5 devices.
Does the framework send 5 commands to Appium for creating 5 driver instances for the 5 devices simultaneously, or, does this process happen one after the other? Thanks.

**Comment by saikrishna321** [comment]
At the stage of creating the driver instance, its already in parallel thread process.
