### ISSUE TITLE
Simultaneous Launch and Test Execution

### ISSUE THREAD

**Issue by rameshgit96** [AppiumTestDistribution/AppiumTestDistribution#668]
Suppose I launch a test across 5 Real Android devices. What I notice is that the app gets launched at different times on each device. However, what I am expecting is that the app gets launched at the same time on each device and proceed with the test execution simultaneously. 

Is there any overhead in the framework that can be reduced or perhaps is there a workaround that can be done to ensure that the process is simultaneous across all devices?

**Comment by chuklov** [comment]
Based on Java lang it is not possible as you running each test on a different Thread. Thread are living in JVM and each has different living time. Start of each will be define by JVM. 

There is nothing much you can do on it.

**Comment by rameshgit96** [comment]
@chuklov: I see. Thank you.
