### ISSUE TITLE
How to Run Runner Class with Platform Name? Getting java.lang.IllegalArgumentException: Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test

### ISSUE THREAD

**Issue by anandbhagwat** [AppiumTestDistribution/AppiumTestDistribution#673]
I am trying to run from IDE itself, When I run the RUnner class below:

`public class RunnerClass {

    @Test()
    public void testApp() throws Exception {
        ATDRunner parallelThread = new ATDRunner();
        List<String> tests = new ArrayList<>();
        tests.add("MyTest");
        System.setProperty("Platform", "android");
        parallelThread.runner("com.org.tests",tests);
    }

}`

I get 
java.lang.IllegalArgumentException: Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test

**Comment by anandbhagwat** [comment]
Hi @saikrishna321 , Can you please help, Like how to add Platform in above code just to run from IDE itself?
I want to debug my code

**Comment by saikrishna321** [comment]
You can go to run configuration in ur IDE and set the environment

**Comment by chetanJTH** [comment]
will you please let me know the reason for an issue I am getting. 
please check the image. 
I just have executed the command: `Platform="android" mvn clean -Dtest=Runner test`

![image](https://user-images.githubusercontent.com/48850556/125280841-2778d680-e333-11eb-8e65-76201f58f0cd.png)

**Comment by saikrishna321** [comment]
Please re-open a new issue with details on exception and also which version of ATD ur using.

**Comment by chetanJTH** [comment]
@saikrishna321 what is ATD?

**Comment by saikrishna321** [comment]
AppiumTestDistribution

**Comment by chetanJTH** [comment]
@saikrishna321 how would i check version?

**Comment by chetanJTH** [comment]
@saikrishna321 it's 12.0.2

**Comment by saikrishna321** [comment]
Please raise a new issue with full logs and details

**Comment by chetanJTH** [comment]
does it store adb logs anywhere becasue it's not even starting appium.

**Comment by chetanJTH** [comment]
@saikrishna321 created a new ticket. please reply there.
