### ISSUE TITLE
Recording during failure is locking the thread.

### ISSUE THREAD

**Issue by Jitu1888** [AppiumTestDistribution/AppiumTestDistribution#686]
Any script fails during dumping the video thread is getting locked.

**Comment by Jitu1888** [comment]
Any update ???

**Comment by saikrishna321** [comment]
Can you please provide a sample code snippet. I’m unable to reproduce

**Comment by Jitu1888** [comment]
Thanks SaiKrishna , Can you please let me know where are recording code written.

**Comment by Jitu1888** [comment]
its really urgent help. if you tell me where the recording command is called? @saikrishna321

**Comment by Jitu1888** [comment]
[Output2.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/4850128/Output2.txt)
line no :9999,please open this file in xcode. @saikrishna321

**Comment by saikrishna321** [comment]
Check this: https://stackoverflow.com/questions/37335/how-to-deal-with-java-lang-outofmemoryerror-java-heap-space-error

This has nothing to do with ATD

**Comment by Jitu1888** [comment]
Thanks for the quick reply, can you tell me where the recording code is been called.

**Comment by saikrishna321** [comment]
https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/master/src/main/java/com/video/recorder/AppiumScreenRecorder.java#L53
