### ISSUE TITLE
Facing isCloudExecution when running android execution

### ISSUE THREAD

**Issue by anvitan-anu** [AppiumTestDistribution/AppiumTestDistribution#723]
I have recently updated the ATD version from 11.0.1 to 11.0.2, after that i am facing Null Pointer Exception in iscloudexecution method and i was using the real devices, and no cloud devices.
I have attached the output in the output.txt file 

[output.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/5033849/output.txt)

**Comment by saikrishna321** [comment]
@anvitan-anu Can you please share your capabilities.json?

**Comment by saikrishna321** [comment]
@WasiqB

**Comment by anvitan-anu** [comment]
This is the capabilities.json
{
"android": {
"platformName": "android",
"platformVersion": "8.1.0",
"browserName": "android.browser.app",
"app": {
"local": "android.temp.app"
},
"deviceName": "android",
"noSign": true,
"automationName": "UIAutomator2",
"newCommandTimeout": 600,
"adbExecTimeout": 60000,
"skipServerInstallation": false,
"noReset": false,
"autoGrantPermissions": true,
"appPackage": "app.package",
"appActivity": "app.activity",
"appium:chromeOptions":{"w3c" : false}
},
"iOS": {
"platformName": "iOS",
"app": {
"device": "iOS.temp.app"
},
"deviceName": "xyz",
"browserName": "iOS.browser.app",
"platformVersion": "11.3.1",
"wdaLaunchTimeout": 240000,
"wdaConnectionTimeout": 240000,
"preventWDAAttachments": true,
"clearSystemFiles": true,
"shouldUseSingletonTestManager": false,
"simpleIsVisibleCheck": true,
"maxTypingFrequency": 10,
"autoGrantPermissions": true,
"autoAcceptAlerts": true,
"automationName": "XCUITest",
"xcodeOrgId": "E75UYQGF7U",
"xcodeSigningId": "iPhone Developer",
"noReset": false,
"webviewConnectRetries": 5,
"webkitResponseTimeout": 50000,
"startIWDP": true,
"newCommandTimeout": 100000,
"safariLogAllCommunication":true,
"useNewWDA": true,
"_comment": "dockerURL",
"fullContextList":true
},
"hostMachines": [
{
"isCloud": false,
"machineIP": "127.0.0.1",
"appiumServerPath": "appium.js"
}
]
}

**Comment by saikrishna321** [comment]
Can you try with this version 

```
<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
</repositories>


<dependency>
	    <groupId>com.github.AppiumTestDistribution</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>fix-723-SNAPSHOT</version>
</dependency>

```

**Comment by anvitan-anu** [comment]
@saikrishna321 Even after updating the AppiumTestDistribution version i face the same issue as mentioned earlier

**Comment by saikrishna321** [comment]
Can you share the error logs now

**Comment by anvitan-anu** [comment]
@saikrishna321 Error logs
 
java.lang.NullPointerException
        at com.appium.manager.AppiumParallelMethodTestListener.isCloudExecution(AppiumParallelMethodTestListener.java:80)
        at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:138)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:60)
        at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
        at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:631)
        at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
        at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
        at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
        at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by saikrishna321** [comment]
Can you share full logs in gist

**Comment by anvitan-anu** [comment]
@saikrishna321 https://gist.github.com/anvitan-anu/c42d1fc6c8cda26403b7e2eceb339b53 please refer the complete logs

**Comment by saikrishna321** [comment]
@anvitan-anu Can you please fix the report portal issue and let me know - https://gist.github.com/anvitan-anu/c42d1fc6c8cda26403b7e2eceb339b53#file-result-txt-L655

**Comment by anvitan-anu** [comment]
@saikrishna321 the report portal issue is from report portal package, which is not responsible for this issue.

**Comment by saikrishna321** [comment]
@anvitan-anu Can you please debug and check if the session creation is failing - https://github.com/AppiumTestDistribution/AppiumTestDistribution/issues/722#issuecomment-672636725

**Comment by anvitan-anu** [comment]
@saikrishna321 Session is getting created

**Comment by anvitan-anu** [comment]
@saikrishna321 few times it works few times it doesn't on android and ios as well any update on this

**Comment by metalimangal** [comment]
Verified this issue, I am getting null pointer exception in AppiumDeviceManager.getAppiumDevice(), in the after invocation step of AppiumParallelMethodTestListener.

public void afterInvocation(IInvokedMethod iInvokedMethod, ITestResult iTestResult) {
        try {
            if (!isCloudExecution() && !isRetry(iTestResult)) { ----------------> Null pointer exception here
                HashMap<String, String> logs = testLogger.endLogging(iTestResult,
                    AppiumDeviceManager.getAppiumDevice().getDevice().getDeviceModel());
                if (atdHost.isPresent() && atdPort.isPresent()) {
                    String url = "http://" + atdHost.get() + ":" + atdPort.get() + "/testresults";
                    sendResultsToAtdService(iTestResult, "Completed", url, logs);
                } else {
                    new FileFilterParser()
                        .getScreenShotPaths(AppiumDeviceManager.getAppiumDevice()
                            .getDevice().getUdid(), iTestResult);
                    testResults.set(logs);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            AppiumDriverManager.getDriver().quit();
            deviceAllocationManager.freeDevice();
            try {
                if (!isCloudExecution()) {
                    appiumDriverManager.stopAppiumDriver();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }




This is happening intermittently, even after the session is created and the devices are available. Please check why AppiumDeviceManager is null in the afterInvocation method. The AppiumDeviceManager is not null in beforeInvocation function in the same java file.

**Comment by saikrishna321** [comment]
Please try the latest v12.0.0

**Comment by anvitan-anu** [comment]
The issue still persist on latest v12.0.0 ATD as well
