### ISSUE TITLE
CustomListener class not found

### ISSUE THREAD

**Issue by geeethub** [AppiumTestDistribution/AppiumTestDistribution#747]
The class LoginTest imports class `CustomListener` from the package `com.appium.config` but there is no class called `CustomListener` in the package `com.appium.config`
<img width="299" alt="Screen Shot 2020-09-15 at 19 04 55" src="https://user-images.githubusercontent.com/54137657/93197293-688d7200-f786-11ea-91b9-f4374f1a411f.png">

**Comment by xiaohanyu** [comment]
Same problem here.

**Comment by emmahuang** [comment]
same problem, any solution?
