### ISSUE TITLE
test stop at " Allocated Device com.appium.manager.AppiumDevice@4e59fa94 for Execution"

### ISSUE THREAD

**Issue by NewBigBug** [AppiumTestDistribution/AppiumTestDistribution#762]
i use atd run my test,but it aways stay at "Allocated Device com.appium.manager.AppiumDevice@4e59fa94 for Execution" ,i can't find any exception in the log. please help me
`[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 15341
[Appium]   logFile: D:\Code\Java\PipiRunner\target\appiumlogs\appium_logs.txt
[Appium]   relaxedSecurityEnabled: true
[Appium] Appium REST http interface listener started on 127.0.0.1:15341
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.18.3"}}
[HTTP] <-- GET /wd/hub/status 200 5 ms - 68
[HTTP] 
十月 23, 2020 10:34:14 上午 com.appium.manager.LocalAppiumManager startAppiumServer
信息: LocalAppiumManagerAppium Server Started at......http://127.0.0.1:15341/wd/hub
十月 23, 2020 10:34:14 上午 com.appium.manager.DeviceAllocationManager allocateDevice
信息: Allocated Device com.appium.manager.AppiumDevice@4e59fa94 for Execution`

**Comment by saikrishna321** [comment]
@NewBigBug Can you please give a sample repo to reproduce
