### ISSUE TITLE
AfterInvocation called without running actual tests

### ISSUE THREAD

**Issue by priyankshah217** [AppiumTestDistribution/AppiumTestDistribution#775]
Found unusual patten while running test using ATD. So as per behaviour, just after installing app in android/ios it immediately called afterInvocation(AppiumParallelMethodTestListner.class). Because of this issue it launches app and immediately closed it and it retry again.

Please find below logs 

https://gist.github.com/priyankshah217/b418f12d407e53f349fb8461e0d7f867

Full Appium logs of run,
https://gist.github.com/priyankshah217/24fb791dcf35d78f0ff75db064a7ef37

**Comment by saikrishna321** [comment]
@priyankshah217 Did the PR fix this issue?

**Comment by priyankshah217** [comment]
@saikrishna321 yes that issue is resolved now.
