### ISSUE TITLE
Facing isCloudExecution when running android execution

### ISSUE THREAD

**Issue by anvitan-anu** [AppiumTestDistribution/AppiumTestDistribution#831]
@saikrishna321 I have re-opened the issue

https://github.com/AppiumTestDistribution/AppiumTestDistribution/issues/723

**Comment by anvitan-anu** [comment]
@saikrishna321 I have attached the logs for ATD latest v12.0.0

https://gist.github.com/anvitan-anu/7b9d5d920b046ff65010025070f83585

**Comment by saikrishna321** [comment]
@anvitan-anu Can you share the appium server logs pls and the capabilites.json

**Comment by anvitan-anu** [comment]
Capabilities.json

`
{
  "android": {
    "platformName": "android",
    "platformVersion": "8.1.0",
    "browserName": "android.browser.app",
    "app": {
      "local": "android.temp.app"
    },
    "deviceName": "android",
    "noSign": true,
    "automationName": "UIAutomator2",
    "newCommandTimeout": 600,
    "adbExecTimeout": 60000,
    "skipServerInstallation": false,
    "noReset": false,
    "autoGrantPermissions": true,
    "appPackage": "app.package",
    "appActivity": "app.activity",
    "appium:chromeOptions":{"w3c" : false}
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "device": "iOS.temp.app"
    },
    "permission": {
      "com.games24x7.rummycircle.ios": {
        "location": "inuse"
      }
    },
    "deviceName": "Rummy’s iPad",
    "browserName": "iOS.browser.app",
    "platformVersion": "11.3.1",
    "wdaLaunchTimeout": 240000,
    "wdaConnectionTimeout": 240000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10,
    "autoGrantPermissions": true,
    "autoAcceptAlerts": true,
    "automationName": "XCUITest",
    "xcodeOrgId": "E75UYQGF7U",
    "xcodeSigningId": "iPhone Developer",
    "noReset": false,
    "webviewConnectRetries": 5,
    "webkitResponseTimeout": 50000,
    "startIWDP": true,
    "newCommandTimeout": 100000,
    "safariLogAllCommunication":true,
    "useNewWDA": true,
    "_comment": "dockerURL",
    "fullContextList":true
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "appiumServerPath": "appium.js"
    }
  ]
}

`

**Comment by saikrishna321** [comment]
@anvitan-anu Why are you giving "browserName": "android.browser.app" with app capabilities as well?

**Comment by saikrishna321** [comment]
@anvitan-anu Try with below caps

```
  "android": {
    "platformName": "android",
    "platformVersion": "8.1.0",
    "app": {
      "local": "https://github.com/shridharkalagi/AppiumSample/raw/master/VodQA.apk"
    },
    "deviceName": "android",
    "noSign": true,
    "automationName": "UIAutomator2",
    "adbExecTimeout": 60000,
    "autoGrantPermissions": true,
    "appium:chromeOptions":{"w3c" : false}
  },

```
