### ISSUE TITLE
No devices connected, But when running through eclipse working.

### ISSUE THREAD

**Issue by Sai417** [AppiumTestDistribution/AppiumTestDistribution#834]
I have given capabilities to iOS device like this, but showing no devices connected!
"iOS": {
"platformName": "iOS",
"deviceName": "SaiPad",
"bundleID": "com.XYZ",
"xcodeSigningId": "iPhone Developer",
"platformVersion": "13.6.1",
"udid": "XXXX-2E",
"wdaLaunchTimeout": 80000,
"wdaConnectionTimeout": 80000,
"preventWDAAttachments": true,
"clearSystemFiles": true,
"shouldUseSingletonTestManager": false,
"simpleIsVisibleCheck": true,
"noReset": true,
"newWDA" : false,
"maxTypingFrequency": 10
},
"hostMachines": [
{
"machineIP": "127.0.0.1",
"appiumServerPath": "/usr/local/lib/node_modules/appium/build/lib/main.js"
}
]

Can you please help me, did I miss anything!

<img width="958" alt="Screenshot 2021-03-22 at 3 20 45 PM" src="https://user-images.githubusercontent.com/36687547/111971264-2f153500-8b22-11eb-91aa-8fabbb52c9d3.png">

**Comment by Sai417** [comment]
when I add simulator it is working and able to do it in simulator.
but my requirement is to done in real device, couldn't able to do it.
Please check , Many Thanks!

**Comment by saikrishna321** [comment]
Make sure your terminal can detect iOS device with command - https://github.com/AppiumTestDistribution/DeviceManager/blob/master/src/main/java/com/github/iOS/IOSManager.java#L20-L21

**Comment by Sai417** [comment]
Please ,can we have a call, im new to Appium, could able to do it.
@saikrishna321
