### ISSUE TITLE
Unable to Test on Real iPhoneXR - No Devices Connected

### ISSUE THREAD

**Issue by ramgiteng** [AppiumTestDistribution/AppiumTestDistribution#837]
Hi,

I am experiencing an issue with executing tests on a real iPhone XR. As soon as I trigger the command to test on a real iPhoneXR device, I am getting the display "Parallel No Devices Connected". 

**Details**:
ATD Version: 11.0.1
Appium Version: 1.15.1
Real Device: iPhone XR
OS Version: 13.3
Example command: CONFIG_FILE="config.properties" udids="(iPhoneXRUDID)" Platform="ios" mvn clean -Dtest.app=Runner test

This probably has something to do with the new UDID format of the iPhone XR, iPhone XS, and iPhone XS Max phones. 
Example: 00008020-008D4548007B4F26

In the following link,
https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/39d0b6e3093526a96614ae372a1bfe28777fdf1e/src/main/java/com/appium/ios/IOSDeviceConfiguration.java

 public final static int IOS_UDID_LENGTH = 40;

The other iPhones have a UDID length of 40, whereas the length of the new format for the specific phones is 25 (including the hyphen).

Would it be possible to override this from the tester's end, or perhaps, could you please add the necessary support to test on iPhone XR, iPhone XS, and iPhone XS Max respectively? Thank you!

**Comment by saikrishna321** [comment]
@ramgiteng This issue has been fixed. Please try version ATD 12.0.0

**Comment by ramgiteng** [comment]
Sure, I will try it out and confirm. Thanks.

**Comment by ramgiteng** [comment]
After upgrading to 12.0.0 in pom.xml, I am experiencing issues with running tests in iOS devices - WDA gets uninstalled and xcodebuild error code 65 appears. However, when I downgrade back to 11.0.1, WDA gets installed on the devices and iOS tests run smoothly.

Do I need to set any special configurations like upgrading XCode or reinstalling WDA manually for running tests on real iOS devices when upgrading to 12.0.0? Thanks

**Comment by saikrishna321** [comment]
Xcode error 65 means it's a signing error on wda

**Comment by ramgiteng** [comment]
Yes, it was an Appium-specific issue. I rebuilt and installed WDA on the device. It worked. Thank you.
