### ISSUE TITLE
Adb command to fetch the chrome version did not work 

### ISSUE THREAD

**Issue by vmaramreddy1** [AppiumTestDistribution/AppiumTestDistribution#849]
In HostMachineDeviceManager.java file , to fetch the chrome version on windows environment we are executing the following command `adb -s udid shell dumpsys package com.android.chrome | grep version name `. this command resulting empty string in windows. It should be changed to `adb -s udid shell "dumpsys package com.android.chrome | grep version name"`. Notice that I have wrapped the entire command inside double quotes which follows the shell word.

**Comment by vmaramreddy1** [comment]
@WasiqB or @saikrishna321 could you please verify and fix it accordingly ?

**Comment by saikrishna321** [comment]
@vmaramreddy1 Thanks for reporting. Happy to review a PR. Could you create a fix for this please? I don't hold a windows machine to test this.

**Comment by vmaramreddy1** [comment]
Hi @saikrishna321 , Could you please review this PR https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/850/files and merge ?

**Comment by vmaramreddy1** [comment]
@saikrishna321 , Please check the below PR and merge the code 
https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/851/commits

**Comment by vmaramreddy1** [comment]
@saikrishna321 , corresponding to the PR that I have raised earlier, please look at the followed commit id: https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/851/commits/8c9b8f023549c659add681adb309f436eab66db7

**Comment by chuklov** [comment]
@saikrishna321  Why do we have this check for iOS devices?  It crashes test now 
`
May 05, 2021 1:20:07 PM com.appium.device.HostMachineDeviceManager getChromeVersionsFor
INFO: Chrome not found on device - '00008020-000539502252002E'
java.util.NoSuchElementException: No value present
	at java.util.OptionalInt.getAsInt(OptionalInt.java:118)
	at com.appium.device.HostMachineDeviceManager.getPathForChromeDriver(HostMachineDeviceManager.java:328)
`

**Comment by saikrishna321** [comment]
@chuklov Thanks for reporting. This is a issue. We can fix as part of this PR
