### ISSUE TITLE
How to add the child element in the pagefactory

### ISSUE THREAD

**Issue by SandeepAppium** [AppiumTestDistribution/AppiumTestDistribution#864]
i have a scenario where the elements are present in grid, and multiple grids are present.
SessionList is the Grid under the grid there are multiple sessions present and id are different in android & ios

Current im doing, like this 
@AndroidFindBy(id ="sessionList")
@iOSXCUITFindBy(id = "session-cell")
public List<MobileElement> sessionList;

from screenflows, im returning the element based on the device, like

for android -return sessionList.findelementById("android");
for ios -return sessionList.findelementById("iOS");

im not sure how to add child element in the pagefactory.

is this the correct approach or anyother alternate or suggestions!

Below is the examle
<img width="1121" alt="Screenshot 2021-06-18 at 4 00 58 PM" src="https://user-images.githubusercontent.com/81696352/122548507-13e99100-d04f-11eb-9f11-13c37307c1f5.png">
Having the parent ID/child id same for multiple.

Need to get the list of child elements based on the parent.
@saikrishna321

**Comment by SandeepAppium** [comment]
@saikrishna321 pls help

**Comment by saikrishna321** [comment]
https://github.com/AppiumTestDistribution/PageObjectPatternAppium/blob/master/src/test/java/com/appium/page/objects/WelcomePageObjects.java#L58-L59

@SandeepAppium Check this

**Comment by Sai417** [comment]
How can we handle one element will be list and other will a mobile element.

**Comment by SandeepAppium** [comment]
How can we handle if parent is list and child one is normal mobile element not list
@saikrishna321
