### ISSUE TITLE
ATD 12.0.2 doesn't work with iOS 

### ISSUE THREAD

**Issue by chuklov** [AppiumTestDistribution/AppiumTestDistribution#871]
HI All, 

I would like to check with you guys if you are going to fix this issue 
 com.appium.device.HostMachineDeviceManager **getChromeVersionsFor**
INFO: Chrome not found on device - 'bd3ccfde1c14ef869656292b0460da522728aedc'
java.util.NoSuchElementException: No value present

`
    private Function<Device, AppiumDevice> getAppiumDevice(String machineIP) {
        return device -> {
            AppiumDevice appiumDevice = new AppiumDevice(device, machineIP);
            try {
                if (appiumDevice.getDevice().isCloud()) {
                    appiumDevice.setPort(8543); //need to make sure for specific cloud
                } else if (IOS) { // here we need to check and exit in case of iOS device
              break; 
                } else {
                    appiumDevice.setPort(new AvailablePorts().getAvailablePort(machineIP));
                    String pathForChromeDriver = getPathForChromeDriver(appiumDevice
                        .getDevice().getUdid());
                    appiumDevice.setChromeDriverExecutable(pathForChromeDriver);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
            return appiumDevice;
        };
    }

`

There cannot be a Chrome version on iOS devices. 

Please resolve it. 

BR

**Comment by saikrishna321** [comment]
This issue is fixed on master. Please use the latest commit from master.

**Comment by saikrishna321** [comment]
Add the below dependencies in your pom.xml (Master)

<dependency>
    <groupId>com.github.AppiumTestDistribution</groupId>
    <artifactId>AppiumTestDistribution</artifactId>
    <version>latest_commit</version>
</dependency>
<repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
</repositories>

Replace the latest_commit with the commit number from master.

**Comment by saikrishna321** [comment]
@chuklov Fixed in v12.0.3. Please take the latest
