### ISSUE TITLE
Run parallel tests on Sauce Labs

### ISSUE THREAD

**Issue by shridharkalagi** [AppiumTestDistribution/AppiumTestDistribution#872]
How do I run tests in parallel on Sauce Labs? I tried with `Parallel` runner and ended on the same error as [here](https://github.com/AppiumTestDistribution/AppiumTestDistribution/issues/845). Is there a workaround to run all my tests on both Android and iOS platforms in Parallel?

**Comment by saikrishna321** [comment]
@shridharkalagi We only support Distribute mode for clouds. If you want to Distribute all your test across android and Distribute all the test across iOS. If yes, then you need to have two runners and then trigger them in parallel in your CI.
