### ISSUE TITLE
How to get distributed execution at class level using ATD

### ISSUE THREAD

**Issue by deepakarorawins** [AppiumTestDistribution/AppiumTestDistribution#890]
Parallel will run all the tests across device- which helps you to get the device coverage
Distribute will distribute all the tests across devices which help you faster execution

Can we restrict distribution at class level (to run whole class on one device and other class on another device) ?
How using ATD ?

**Comment by saikrishna321** [comment]
Yes, set RUNNER_LEVEL="parallel" this will run tests at class level

**Comment by deepakarorawins** [comment]
Now, I've noticed that there is no effect for my listener which I've added in config.properties.
I was following  "PagePatternAppium" then I tried putting config.properties at different places, it never get picked up.
Could you please suggest right step to provide custom listener if I'm doing it wrong ?

![image](https://user-images.githubusercontent.com/30565176/134339399-7db988ad-b40e-487f-9b10-325e2334d280.png)

**Comment by saikrishna321** [comment]
@deepakarorawins Thanks for reporting. Looks like a bug. Let me investigate on it.

**Comment by deepakarorawins** [comment]
I tried to fix and raised a PR: -  [ https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/891]( https://github.com/AppiumTestDistribution/AppiumTestDistribution/pull/891)


It says...
First-time contributors need a maintainer to approve running workflows. Learn more.
1 failing, 4 cancelled, and 5 successful checks

**Comment by saikrishna321** [comment]
@deepakarorawins Thanks for the contribution. I have merged the PR and make a release soon.
