### ISSUE TITLE
Not able to install dependencies with the sample project  PageObjectPatternAppium

### ISSUE THREAD

**Issue by abubakarafzal** [AppiumTestDistribution/AppiumTestDistribution#899]
Clone the repo and open in IntelliJ.  Use the command mvn clean install and always face the error

`Failure to find com.epam.reportportal:agent-java-cucumber6:pom:5.0.0-RC-1 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced`

![image](https://user-images.githubusercontent.com/49385095/138530135-430d0a5f-ac6e-4e11-bbad-f5f3f318c4a2.png)

**Comment by ganjarpanji** [comment]
im facing the same issue
