### ISSUE TITLE
Is it possible to use this in webdriverio tests? 

### ISSUE THREAD

**Issue by EINBOX** [AppiumTestDistribution/AppiumTestDistribution#912]
Hello,
I have a requirement that I want to run tests on iOS and on Android in parallel, can you guide me to use this appium test distribution?
Is it OK if we do configuration? As below
const host = '127.0.0.1'; const port = 4730; config.capabilities = [ { services: [ ['appium', { args: { debugLogSpacing: true, }, command: 'appium', }, ], ], specs: [ "./test/specs/test.spec.js" ], maxInstances: 2, // For iOS/android bases mobile device capabilities: [{ port: 4730, //platformName: 'iOS', automationName: 'XCUITest', platformName: 'iOS', deviceName: 'iPhone 6', browserName: 'Safari', clearSystemFiles: true, acceptInsecureCerts: true, }, { port: 4723, automationName: 'uiautomator2', platformName: 'Android', deviceName: AndroidInfo.deviceName(), browserName: 'chrome', commandTimeout: '7200', noReset: false, }] } ]; exports.config = config;

**Comment by saikrishna321** [comment]
@EINBOX This supports only java client. If you want to try with WDIO look at something similar at server side which support from appium 2.0 https://github.com/AppiumTestDistribution/appium-device-farm
