### ISSUE TITLE
If instrument crashes and appium driver didnt start.

### ISSUE THREAD

**Issue by Jitu1888** [AppiumTestDistribution/AppiumTestDistribution#978]
When I am going through the code for AppiumDriverManager.java: previously we were throwing exceptions when the driver failed. But now we are not throwing any exception for that reason execution is getting stuck. Because in  getNextAvailableDevice you guys are making the thread suspend.

**Comment by Jitu1888** [comment]
@saikrishna321  Can you please help us with this part urgently?

**Comment by saikrishna321** [comment]
Thanks for raising the issue. As you have already spotted the issue can u please raise a PR and I will review

**Comment by saikrishna321** [comment]
Please try with latest version
