### ISSUE TITLE
Support latest java client

### ISSUE THREAD

**Issue by SrinivasanTarget** [AppiumTestDistribution/AppiumTestDistribution#983]

**Comment by samagarw** [comment]
Is any progress on java client for the device manager to lock and release the devices from appium-device-farm ? @SrinivasanTarget

**Comment by saikrishna321** [comment]
@samagarw Can you raise this discussion in appium-device-farm repo to help taking it forward - https://github.com/AppiumTestDistribution/appium-device-farm
